'use strict';
const http=require('http');const fs=require('fs');const path=require('path');const os=require('os');
const Router=require('./router');const C=require('./core');require('./db');
const router=new Router();
require('./routes_auth')(router);require('./routes_v24')(router);require('./routes_clients')(router);require('./routes_workforce')(router);require('./routes_schedule')(router);require('./routes_finance')(router);require('./routes_ops')(router);require('./routes_reports')(router);
const ROOT=path.join(__dirname,'..');
function mime(file){const ext=path.extname(file).toLowerCase();return{'.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.ico':'image/x-icon'}[ext]||'application/octet-stream';}
function serveStatic(req,res,url){if(!['/app.css','/app.js'].includes(url.pathname))return false;const file=path.join(ROOT,'public',url.pathname.slice(1));if(!fs.existsSync(file))return false;res.statusCode=200;res.setHeader('Content-Type',mime(file));res.setHeader('Cache-Control','no-cache');res.end(fs.readFileSync(file));return true;}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(serveStatic(req,res,url))return;if(url.pathname==='/health')return C.json(res,{status:'ok',version:'2.6.0',database:'sqlite',docker:false});const ctx=C.loadAuth(req);if(ctx?.user?.must_change_password&&!['/minha-senha','/logout'].includes(url.pathname))return C.redirect(res,'/minha-senha');const m=router.match(req.method,url.pathname);if(!m)return C.send(res,404,C.errorPage('Página não encontrada','O endereço solicitado não existe.'));const q=Object.fromEntries(url.searchParams.entries());await m.handler(req,res,ctx,q,m.params);}catch(e){console.error('[ERRO]',e);if(!res.headersSent)C.send(res,500,C.errorPage('Erro interno',process.env.DEBUG==='1'?e.stack||e.message:'Ocorreu um erro ao processar a operação.'));else try{res.end()}catch{}}});
const PORT=Number(process.env.PORT||3000),HOST=process.env.HOST||'127.0.0.1';
const PID_FILE=path.join(ROOT,'data','server.pid');try{fs.writeFileSync(PID_FILE,String(process.pid))}catch{}
server.listen(PORT,HOST,()=>{console.log('');console.log('========================================================');console.log(' CENTRAL DE GESTAO EMPRESARIAL - SEM DOCKER');console.log('========================================================');console.log(` Acesse neste computador: http://localhost:${PORT}`);if(HOST!=='127.0.0.1'&&HOST!=='localhost'){const nets=os.networkInterfaces();for(const list of Object.values(nets))for(const n of list||[])if(n.family==='IPv4'&&!n.internal)console.log(` Rede local:              http://${n.address}:${PORT}`);}console.log(' Banco persistente:       data/central-gestao.sqlite');console.log(' Para encerrar: feche esta janela ou use PARAR_WINDOWS.bat');console.log('========================================================');console.log('');});
function stop(){try{fs.unlinkSync(PID_FILE)}catch{}server.close(()=>process.exit(0));setTimeout(()=>process.exit(0),2000).unref();}
process.on('SIGINT',stop);process.on('SIGTERM',stop);
