'use strict';
const {run,get,all,id,now,hashPassword,verifyPassword,transaction}=require('./db');
const C=require('./core'); const U=require('./ui');
function permsForm(ctx,userId){
  const map={}; if(userId)for(const p of all('SELECT * FROM user_permissions WHERE user_id=:u',{u:userId}))map[p.module]=p;
  const rows=Object.entries(C.MODULES).map(([m,label])=>{const p=map[m]||{};return `<tr><td><b>${C.esc(label)}</b></td>${C.ACTIONS.map(a=>a==='delete'?`<td><span class="badge muted" title="Exclusão permanente é exclusiva do administrador">ADMIN</span></td>`:`<td><label class="check"><input type="checkbox" name="perm_${m}_${a}" value="1" ${Number(p['can_'+a])?'checked':''}></label></td>`).join('')}</tr>`}).join('');
  return `<div class="alert warn">Exclusões permanentes são operações críticas e ficam restritas a ADMIN/SUPERADMIN. Usuários comuns podem receber permissões de visualizar, criar, editar, importar, exportar e aprovar.</div><div class="table-wrap"><table><thead><tr><th>Módulo</th>${C.ACTIONS.map(a=>`<th>${({view:'Ver',create:'Criar',edit:'Editar',delete:'Excluir',import:'Importar',export:'Exportar',approve:'Aprovar'})[a]}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div>`;
}
function savePerms(org,userId,b){
  run('DELETE FROM user_permissions WHERE user_id=:u',{u:userId});
  for(const m of Object.keys(C.MODULES)){
    const vals={}; let any=false; for(const a of C.ACTIONS){vals[a]=a==='delete'?0:C.bool(b[`perm_${m}_${a}`]); if(vals[a])any=true;} if(!any)continue;
    run(`INSERT INTO user_permissions(id,organization_id,user_id,module,can_view,can_create,can_edit,can_delete,can_import,can_export,can_approve)
    VALUES(:id,:o,:u,:m,:v,:c,:e,:d,:i,:x,:a)`,{id:id(),o:org,u:userId,m,v:vals.view,c:vals.create,e:vals.edit,d:vals.delete,i:vals.import,x:vals.export,a:vals.approve});
  }
}
module.exports=function(r){
 r.get('/login',async(req,res,ctx,q)=>{if(ctx)return C.redirect(res,'/');C.send(res,200,U.loginPage(q.msg||''));});
 r.post('/login',async(req,res)=>{const b=await C.parseBody(req),cpf=C.cleanLoginId(b.cpf),key=`${C.clientIp(req)}:${cpf}`;if(!C.loginAllowed(key))return C.send(res,429,U.loginPage('Muitas tentativas. Aguarde alguns minutos.'));
   const users=all(`SELECT u.*,o.name organization_name FROM users u JOIN organizations o ON o.id=u.organization_id WHERE u.cpf=:cpf AND u.active=1 AND o.active=1`,{cpf});
   const u=users.find(x=>verifyPassword(b.password,x.password_hash)); if(!u){C.recordLoginFailure(key);return C.send(res,401,U.loginPage('CPF ou senha inválidos.'));}
   C.createSession(res,req,u.id);run('UPDATE users SET last_login_at=:t WHERE id=:id',{t:now(),id:u.id});C.audit({user:{id:u.id,organization_id:u.organization_id,name:u.name,cpf:u.cpf}},req,'LOGIN','users',u.id,null,{login:true});C.redirect(res,u.must_change_password?'/minha-senha':'/');
 });
 r.get('/logout',async(req,res,ctx)=>{if(ctx)C.audit(ctx,req,'LOGOUT','users',ctx.user.id,null,{logout:true});C.destroySession(req,res);C.redirect(res,'/login');});
 r.get('/minha-senha',async(req,res,ctx,q)=>{if(!C.requireAuth(ctx,res))return;const body=U.panel('Alterar minha senha',`<form method="post">${U.csrf(ctx)}${U.formGrid(U.input('current','Senha atual','',{type:'password',required:true})+U.input('password','Nova senha','',{type:'password',required:true,placeholder:'mínimo 8 caracteres'})+U.input('confirm','Confirmar nova senha','',{type:'password',required:true}),`<button class="btn primary">Salvar nova senha</button>`)}</form>`);C.send(res,200,U.layout(ctx,'Minha senha',body,'/minha-senha',{msg:q.msg,mt:q.mt}));});
 r.post('/minha-senha',async(req,res,ctx)=>{if(!C.requireAuth(ctx,res))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida','Atualize a página e tente novamente.'));const u=get('SELECT * FROM users WHERE id=:id',{id:ctx.user.id});if(!verifyPassword(b.current,u.password_hash))return C.redirect(res,C.flashUrl('/minha-senha','Senha atual incorreta.','err'));if(String(b.password||'').length<8||b.password!==b.confirm)return C.redirect(res,C.flashUrl('/minha-senha','A nova senha deve ter ao menos 8 caracteres e as confirmações devem coincidir.','err'));run('UPDATE users SET password_hash=:h,must_change_password=0,updated_at=:t WHERE id=:id',{h:hashPassword(b.password),t:now(),id:u.id});C.audit(ctx,req,'PASSWORD_CHANGE','users',u.id,null,{password_changed:true});C.redirect(res,C.flashUrl('/minha-senha','Senha alterada com sucesso.'));});

 r.get('/',async(req,res,ctx)=>{if(!C.requirePerm(ctx,res,'dashboard'))return;const o=ctx.user.organization_id;const today=C.localDate();const clients=Number(get('SELECT COUNT(*) c FROM clients WHERE organization_id=:o AND active=1',{o}).c);const employees=Number(get("SELECT COUNT(*) c FROM employees WHERE organization_id=:o AND status='ACTIVE'",{o}).c);const receivable=Number(get("SELECT COALESCE(SUM(amount-paid_amount),0) s FROM financial_entries WHERE organization_id=:o AND entry_type='RECEIVABLE' AND status NOT IN ('PAID','CANCELLED')",{o}).s);const payable=Number(get("SELECT COALESCE(SUM(amount-paid_amount),0) s FROM financial_entries WHERE organization_id=:o AND entry_type='PAYABLE' AND status NOT IN ('PAID','CANCELLED')",{o}).s);const contracts=all('SELECT c.*,cl.trade_name,cl.legal_name FROM contracts c JOIN clients cl ON cl.id=c.client_id WHERE c.organization_id=:o AND c.active=1 ORDER BY c.end_date',{o}).map(x=>({...x,st:C.statusContract(x.end_date,x.renewal_status,x.active)}));const risky=contracts.filter(x=>['90','30','4','expired','await'].includes(x.st.key));const expired=risky.filter(x=>x.st.key==='expired'||(x.st.key==='await'&&Number(x.st.days)<0)).length;const d4=risky.filter(x=>x.st.key==='4').length;const d30=risky.filter(x=>x.st.key==='30').length;const d90=risky.filter(x=>x.st.key==='90').length;const awaiting=risky.filter(x=>x.st.key==='await').length;const uniforms=all("SELECT um.*,uc.name uniform_name,e.name employee_name FROM uniform_movements um JOIN uniform_catalog uc ON uc.id=um.uniform_id LEFT JOIN employees e ON e.id=um.employee_id WHERE um.organization_id=:o AND um.next_exchange_date IS NOT NULL AND um.next_exchange_date<=date('now','+30 day') ORDER BY um.next_exchange_date LIMIT 10",{o});const expDocs=all(`SELECT d.*,co.contract_number,cl.trade_name,cl.legal_name FROM contract_documents d JOIN contracts co ON co.id=d.contract_id JOIN clients cl ON cl.id=co.client_id WHERE d.organization_id=:o AND d.expiration_date IS NOT NULL AND d.expiration_date<=date('now','+90 day') ORDER BY d.expiration_date LIMIT 30`,{o});const tickets=Number(get("SELECT COUNT(*) c FROM tickets WHERE organization_id=:o AND status NOT IN ('CLOSED','CANCELLED')",{o}).c);const low=Number(get('SELECT COUNT(*) c FROM inventory_items WHERE organization_id=:o AND current_stock<=minimum_stock AND active=1',{o}).c);const unreconciled=Number(get('SELECT COUNT(*) c FROM financial_payments WHERE organization_id=:o AND active=1 AND bank_account_id IS NOT NULL AND reconciled=0',{o}).c);
   const k=`<div class="grid">${U.card('Clientes ativos',clients)}${U.card('Colaboradores ativos',employees)}${U.card('A receber',U.money(receivable))}${U.card('A pagar',U.money(payable))}${U.card('Baixas a conciliar',unreconciled,'movimentos financeiros')}${U.card('Chamados abertos',tickets)}${U.card('Estoque em alerta',low)}</div>`;
   const alerts=`<div class="grid">${U.card('Contratos vencidos',expired,'exigem ação',expired?'danger':'')}${U.card('Vencem em até 4 dias',d4)}${U.card('Vencem em até 30 dias',d30)}${U.card('Vencem em até 90 dias',d90)}${U.card('Aguardando renovação',awaiting)}</div>`;
   const crows=risky.slice(0,30).map(x=>`<tr><td><a href="/clientes/${x.client_id}"><b>${C.esc(x.trade_name||x.legal_name)}</b></a></td><td><a href="/contratos/${x.id}">${C.esc(x.contract_number||'-')}</a></td><td>${U.dateBR(x.end_date)}</td><td>${x.st.days===null||x.st.days===undefined?'-':x.st.days<0?`<b class="danger-text">${Math.abs(x.st.days)} dia(s) vencido</b>`:`${x.st.days} dia(s) restantes`}</td><td>${U.badge(x.st.label,x.st.class)}</td></tr>`);const urows=uniforms.map(x=>`<tr><td>${C.esc(x.employee_name||'-')}</td><td>${C.esc(x.uniform_name)}</td><td>${U.dateBR(x.next_exchange_date)}</td><td>${x.next_exchange_date<today?U.badge('Atrasado','danger'):U.badge('Próximo','warn')}</td></tr>`);const drows=expDocs.map(x=>{const days=Math.round((new Date(x.expiration_date+'T12:00:00')-new Date(today+'T12:00:00'))/86400000),status=days<0?U.badge(`Vencido há ${Math.abs(days)} dia(s)`,'danger'):days===0?U.badge('Vence hoje','danger'):U.badge(`Vence em ${days} dia(s)`,days<=30?'warn':'info');return `<tr><td>${C.esc(x.trade_name||x.legal_name)}</td><td><a href="/contratos/${x.contract_id}/documentos">${C.esc(x.contract_number||'-')}</a></td><td>${C.esc(x.title)}</td><td>${U.dateBR(x.expiration_date)}</td><td>${status}</td></tr>`});const body=k+alerts+`<div class="grid2">${U.panel('Contratos que exigem atenção',U.table(['Cliente','Contrato','Fim','Prazo','Status'],crows))}${U.panel('Trocas de uniforme próximas',U.table(['Colaborador','Item','Próxima troca','Situação'],urows))}</div>`+U.panel('Documentos / apólices com vencimento em até 90 dias',U.table(['Cliente','Contrato','Documento','Vencimento','Alerta'],drows));C.send(res,200,U.layout(ctx,'Dashboard',body,'/'));
 });

 r.get('/usuarios',async(req,res,ctx,q)=>{if(!C.requirePerm(ctx,res,'users'))return;const o=ctx.user.organization_id;const users=all('SELECT * FROM users WHERE organization_id=:o ORDER BY active DESC,name',{o});const rows=users.map(u=>{const manageable=C.isAdmin(ctx)&&(u.role!=='SUPERADMIN'||ctx.user.role==='SUPERADMIN');const actions=manageable?`<a class="btn sm" href="/usuarios/${u.id}/editar">Editar</a>${u.id!==ctx.user.id?`<form method="post" action="/usuarios/${u.id}/toggle">${U.csrf(ctx)}<button class="btn sm" data-confirm="Alterar situação deste usuário?">${u.active?'Desativar':'Ativar'}</button></form><form method="post" action="/usuarios/${u.id}/excluir">${U.csrf(ctx)}<button class="btn sm danger" data-confirm="Excluir definitivamente este usuário? O histórico de auditoria será preservado.">Excluir</button></form>`:''}`:'<span class="muted">Somente administrador</span>';return `<tr><td><b>${C.esc(u.name)}</b><br><small class="muted">${C.esc(u.email||'')}</small></td><td>${C.esc(u.cpf)}</td><td>${U.badge(u.role,u.role==='USER'?'muted':'info')}</td><td>${u.active?U.badge('Ativo','ok'):U.badge('Inativo','danger')}</td><td>${U.dateTimeBR(u.last_login_at)}</td><td><div class="row-actions">${actions}</div></td></tr>`});const actions=C.isAdmin(ctx)?'<a class="btn primary" href="/usuarios/novo">Novo usuário</a>':'';C.send(res,200,U.layout(ctx,'Usuários',U.panel('Usuários da empresa',`<div class="alert warn"><b>Controle administrativo:</b> somente ADMIN/SUPERADMIN pode criar usuários, alterar perfis/permissões, ativar, desativar ou excluir acessos.</div>`+U.table(['Nome','CPF / ID','Perfil','Situação','Último login','Ações'],rows)), '/usuarios',{msg:q.msg,mt:q.mt,actions}));});
 r.get('/usuarios/novo',async(req,res,ctx)=>{if(!C.requireAdmin(ctx,res))return;const roles=[['USER','Usuário'],['ADMIN','Administrador'],...(ctx.user.role==='SUPERADMIN'?[['SUPERADMIN','Superadministrador']]:[])];const f=`<form method="post" action="/usuarios">${U.csrf(ctx)}${U.formGrid(U.input('name','Nome completo','',{required:true})+U.input('cpf','CPF / ID de acesso','',{required:true,placeholder:'CPF ou ID, ex.: financeiro01'})+U.input('email','E-mail','',{type:'email'})+U.select('role','Perfil','USER',roles,{blank:false})+U.input('password','Senha inicial','',{type:'password',required:true,placeholder:'mínimo 8 caracteres'})+U.check('must_change_password','Obrigar troca de senha no primeiro acesso',true),`<a class="btn" href="/usuarios">Cancelar</a><button class="btn primary">Criar usuário</button>`)}<div class="panel-head"><h2>Permissões por módulo</h2></div>${permsForm(ctx,null)}</form>`;C.send(res,200,U.layout(ctx,'Novo usuário',U.panel('Dados e acessos',f),'/usuarios'));});
 r.post('/usuarios',async(req,res,ctx)=>{if(!C.requireAdmin(ctx,res))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida','Atualize e tente novamente.'));const cpf=C.cleanLoginId(b.cpf);if(!C.validLoginId(cpf))return C.redirect(res,C.flashUrl('/usuarios/novo','CPF/ID inválido. Use um CPF ou um ID com 3 a 50 caracteres: letras, números, ponto, hífen, _ ou @.','err'));if(String(b.password||'').length<8)return C.redirect(res,C.flashUrl('/usuarios/novo','A senha inicial deve ter pelo menos 8 caracteres.','err'));if(!String(b.name||'').trim())return C.redirect(res,C.flashUrl('/usuarios/novo','Informe o nome completo do usuário.','err'));if(get('SELECT id FROM users WHERE cpf=:c',{c:cpf}))return C.redirect(res,C.flashUrl('/usuarios/novo','Já existe usuário com este CPF/ID.','err'));let role=b.role==='ADMIN'?'ADMIN':'USER';if(b.role==='SUPERADMIN'&&ctx.user.role==='SUPERADMIN')role='SUPERADMIN';const uid=id(),t=now();transaction(()=>{run(`INSERT INTO users(id,organization_id,cpf,name,email,password_hash,role,active,must_change_password,created_at,updated_at) VALUES(:id,:o,:c,:n,:e,:h,:r,1,:m,:t,:t)`,{id:uid,o:ctx.user.organization_id,c:cpf,n:String(b.name).trim(),e:String(b.email||'').trim(),h:hashPassword(b.password),r:role,m:C.bool(b.must_change_password),t});savePerms(ctx.user.organization_id,uid,b)});C.audit(ctx,req,'CREATE','users',uid,null,{name:b.name,cpf,role});C.redirect(res,C.flashUrl('/usuarios','Usuário criado.'));});
 r.get('/usuarios/:id/editar',async(req,res,ctx,q,p)=>{if(!C.requireAdmin(ctx,res))return;const u=get('SELECT * FROM users WHERE id=:id AND organization_id=:o',{id:p.id,o:ctx.user.organization_id});if(!u)return C.send(res,404,C.errorPage('Usuário não encontrado',''));if(u.role==='SUPERADMIN'&&ctx.user.role!=='SUPERADMIN')return C.send(res,403,C.errorPage('Acesso restrito','Somente um SUPERADMIN pode alterar outro SUPERADMIN.'));const roles=[['USER','Usuário'],['ADMIN','Administrador'],...(ctx.user.role==='SUPERADMIN'?[['SUPERADMIN','Superadministrador']]:[])];const f=`<form method="post" action="/usuarios/${u.id}">${U.csrf(ctx)}${U.formGrid(U.input('name','Nome completo',u.name,{required:true})+U.input('cpf','CPF / ID de acesso',u.cpf,{required:true,placeholder:'CPF ou ID, ex.: financeiro01'})+U.input('email','E-mail',u.email||'',{type:'email'})+U.select('role','Perfil',u.role,roles,{blank:false})+U.input('password','Nova senha (opcional)','',{type:'password',placeholder:'deixe vazio para manter'})+U.check('must_change_password','Obrigar troca de senha',Number(u.must_change_password)),`<a class="btn" href="/usuarios">Voltar</a><button class="btn primary">Salvar alterações</button>`)}<div class="panel-head"><h2>Permissões por módulo</h2></div>${permsForm(ctx,u.id)}</form>`;C.send(res,200,U.layout(ctx,'Editar usuário',U.panel(u.name,f),'/usuarios',{msg:q.msg,mt:q.mt}));});
 r.post('/usuarios/:id',async(req,res,ctx,q,p)=>{if(!C.requireAdmin(ctx,res))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const u=get('SELECT * FROM users WHERE id=:id AND organization_id=:o',{id:p.id,o:ctx.user.organization_id});if(!u)return C.send(res,404,C.errorPage('Usuário não encontrado',''));if(u.role==='SUPERADMIN'&&ctx.user.role!=='SUPERADMIN')return C.send(res,403,C.errorPage('Acesso restrito','Somente um SUPERADMIN pode alterar outro SUPERADMIN.'));const cpf=C.cleanLoginId(b.cpf);if(!C.validLoginId(cpf))return C.redirect(res,C.flashUrl(`/usuarios/${u.id}/editar`,'CPF/ID inválido. Use um CPF ou um ID com 3 a 50 caracteres: letras, números, ponto, hífen, _ ou @.','err'));const dup=get('SELECT id FROM users WHERE cpf=:c AND id<>:id',{c:cpf,id:u.id});if(dup)return C.redirect(res,C.flashUrl(`/usuarios/${u.id}/editar`,'CPF/ID já utilizado.','err'));let role=b.role==='ADMIN'?'ADMIN':'USER';if(b.role==='SUPERADMIN'&&ctx.user.role==='SUPERADMIN')role='SUPERADMIN';transaction(()=>{run('UPDATE users SET name=:n,cpf=:c,email=:e,role=:r,must_change_password=:m,updated_at=:t WHERE id=:id',{n:String(b.name||'').trim(),c:cpf,e:String(b.email||'').trim(),r:role,m:C.bool(b.must_change_password),t:now(),id:u.id});if(b.password){if(String(b.password).length<8)throw new Error('A nova senha deve ter ao menos 8 caracteres.');run('UPDATE users SET password_hash=:h,must_change_password=1 WHERE id=:id',{h:hashPassword(b.password),id:u.id})}savePerms(ctx.user.organization_id,u.id,b)});C.audit(ctx,req,'UPDATE','users',u.id,{name:u.name,cpf:u.cpf,role:u.role},{name:b.name,cpf,role});C.redirect(res,C.flashUrl(`/usuarios/${u.id}/editar`,'Usuário atualizado.'));});
 r.post('/usuarios/:id/excluir',async(req,res,ctx,q,p)=>{if(!C.requireAdmin(ctx,res))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));if(p.id===ctx.user.id)return C.redirect(res,C.flashUrl('/usuarios','Você não pode excluir seu próprio usuário.','err'));const u=get('SELECT * FROM users WHERE id=:id AND organization_id=:o',{id:p.id,o:ctx.user.organization_id});if(!u)return C.redirect(res,'/usuarios');if(u.role==='SUPERADMIN'&&ctx.user.role!=='SUPERADMIN')return C.send(res,403,C.errorPage('Acesso restrito','Somente um SUPERADMIN pode excluir outro SUPERADMIN.'));C.audit(ctx,req,'DELETE','users',u.id,{name:u.name,cpf:u.cpf,role:u.role},null);run('DELETE FROM users WHERE id=:id AND organization_id=:o',{id:u.id,o:ctx.user.organization_id});C.redirect(res,C.flashUrl('/usuarios','Usuário excluído. O registro de auditoria foi preservado.'));});
 r.post('/usuarios/:id/toggle',async(req,res,ctx,q,p)=>{if(!C.requireAdmin(ctx,res))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));if(p.id===ctx.user.id)return C.redirect(res,C.flashUrl('/usuarios','Você não pode desativar seu próprio usuário.','err'));const u=get('SELECT * FROM users WHERE id=:id AND organization_id=:o',{id:p.id,o:ctx.user.organization_id});if(!u)return C.send(res,404,C.errorPage('Usuário não encontrado',''));if(u.role==='SUPERADMIN'&&ctx.user.role!=='SUPERADMIN')return C.send(res,403,C.errorPage('Acesso restrito','Somente um SUPERADMIN pode alterar outro SUPERADMIN.'));run('UPDATE users SET active=:a,updated_at=:t WHERE id=:id',{a:u.active?0:1,t:now(),id:u.id});run('DELETE FROM sessions WHERE user_id=:id',{id:u.id});C.audit(ctx,req,u.active?'DEACTIVATE':'ACTIVATE','users',u.id,{active:u.active},{active:u.active?0:1});C.redirect(res,C.flashUrl('/usuarios','Situação alterada.'));});
};
