'use strict';
const {run,get,all,id,now,transaction}=require('./db');
const C=require('./core');
const U=require('./ui');

const entryTypes=[['PAYABLE','Conta a pagar'],['RECEIVABLE','Conta a receber']];
const today=()=>C.localDate();

function entryStat(e){
  if(e.status==='CANCELLED')return['Cancelado','muted'];
  if(Number(e.paid_amount)>=Number(e.amount)-0.005)return['Pago','ok'];
  if(Number(e.paid_amount)>0)return['Parcial','warn'];
  if(e.due_date<today())return['Vencido','danger'];
  return['Pendente','info'];
}
function bankOptions(o,includeInactive=false){
  return all(`SELECT id,name,bank_name,active FROM bank_accounts WHERE organization_id=:o ${includeInactive?'':'AND active=1'} ORDER BY active DESC,name`,{o})
    .map(b=>[b.id,`${b.name}${b.bank_name?' · '+b.bank_name:''}${b.active?'':' · INATIVA'}`]);
}
function recalcEntry(o,entryId){
  const e=get('SELECT * FROM financial_entries WHERE id=:id AND organization_id=:o',{id:entryId,o});
  if(!e)return null;
  const p=get(`SELECT COALESCE(SUM(amount),0) paid,MAX(movement_date) last_date FROM financial_payments
    WHERE organization_id=:o AND financial_entry_id=:e AND active=1`,{o,e:entryId});
  const paid=Math.min(Number(e.amount),Number(p?.paid||0));
  const status=e.status==='CANCELLED'?'CANCELLED':paid>=Number(e.amount)-0.005?'PAID':paid>0?'PARTIAL':'PENDING';
  const last=get(`SELECT bank_account_id,payment_method FROM financial_payments WHERE organization_id=:o AND financial_entry_id=:e AND active=1 ORDER BY movement_date DESC,created_at DESC LIMIT 1`,{o,e:entryId});
  run(`UPDATE financial_entries SET paid_amount=:paid,payment_date=:d,status=:s,bank_account_id=:b,payment_method=COALESCE(NULLIF(:pm,''),payment_method),updated_at=:t
       WHERE id=:id AND organization_id=:o`,{paid,d:p?.last_date||null,s:status,b:last?.bank_account_id||null,pm:last?.payment_method||'',t:now(),id:entryId,o});
  return get('SELECT * FROM financial_entries WHERE id=:id AND organization_id=:o',{id:entryId,o});
}
function range(q){
  const t=today();
  const first=t.slice(0,8)+'01';
  const from=C.normDate(q.from)||first;
  const to=C.normDate(q.to)||t;
  return from<=to?{from,to}:{from:to,to:from};
}
function txOrigin(t){return t.imported?'Importado':t.movement_origin==='FINANCE'?'Financeiro':'Manual';}

module.exports=function(r){
  // ---------------- FINANCEIRO ----------------
  r.get('/financeiro',async(req,res,ctx,q)=>{
    if(!C.requirePerm(ctx,res,'finance'))return;
    const o=ctx.user.organization_id,type=String(q.type||''),s=String(q.s||''),status=String(q.status||'');
    const rows=all(`SELECT f.*,fc.name category_name,cl.trade_name,cl.legal_name,ba.name bank_name,
      (SELECT MAX(p.movement_date) FROM financial_payments p WHERE p.financial_entry_id=f.id AND p.active=1) last_payment_date,
      (SELECT COUNT(*) FROM financial_payments p WHERE p.financial_entry_id=f.id AND p.active=1) payment_count
      FROM financial_entries f LEFT JOIN finance_categories fc ON fc.id=f.category_id LEFT JOIN clients cl ON cl.id=f.client_id LEFT JOIN bank_accounts ba ON ba.id=f.bank_account_id
      WHERE f.organization_id=:o AND (:type='' OR f.entry_type=:type) AND (:s='' OR f.description LIKE :like OR f.document_number LIKE :like OR f.supplier_name LIKE :like)
      ORDER BY f.due_date DESC,f.created_at DESC LIMIT 1500`,{o,type,s,like:`%${s}%`}).filter(e=>!status||entryStat(e)[0].toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')===status);
    const tr=rows.map(e=>{const [sl,sc]=entryStat(e);return `<tr>
      <td>${U.badge(e.entry_type==='PAYABLE'?'Pagar':'Receber',e.entry_type==='PAYABLE'?'warn':'info')}</td>
      <td><a href="/financeiro/${e.id}/detalhes"><b>${C.esc(e.description)}</b></a><br><small class="muted">${C.esc(e.category_name||e.supplier_name||e.trade_name||e.legal_name||'')}</small></td>
      <td>${U.dateBR(e.due_date)}</td><td class="right">${U.money(e.amount)}</td><td class="right">${U.money(e.paid_amount)}</td>
      <td>${e.last_payment_date?`${U.dateBR(e.last_payment_date)}<br><small>${C.esc(e.bank_name||'')}</small>`:'-'}</td><td>${U.badge(sl,sc)}</td>
      <td><div class="row-actions"><a class="btn sm" href="/financeiro/${e.id}/detalhes">Abrir</a>${C.can(ctx,'finance','edit')?`<a class="btn sm" href="/financeiro/${e.id}/editar">Editar</a>${sl!=='Pago'&&sl!=='Cancelado'?`<a class="btn sm primary" href="/financeiro/${e.id}/baixar">Baixar</a>`:''}${sl!=='Cancelado'&&Number(e.paid_amount)===0?`<form method="post" action="/financeiro/${e.id}/cancelar">${U.csrf(ctx)}<button class="btn sm">Cancelar</button></form>`:''}`:''}${C.isAdmin(ctx)?`<form method="post" action="/financeiro/${e.id}/excluir">${U.csrf(ctx)}<button class="btn sm danger" data-confirm="Excluir definitivamente este lançamento? Operação exclusiva do administrador.">Excluir</button></form>`:''}</div></td></tr>`});
    const pendingPay=Number(get("SELECT COALESCE(SUM(amount-paid_amount),0)s FROM financial_entries WHERE organization_id=:o AND entry_type='PAYABLE' AND status<>'CANCELLED' AND paid_amount<amount",{o}).s);
    const pendingRec=Number(get("SELECT COALESCE(SUM(amount-paid_amount),0)s FROM financial_entries WHERE organization_id=:o AND entry_type='RECEIVABLE' AND status<>'CANCELLED' AND paid_amount<amount",{o}).s);
    const paidMonth=Number(get("SELECT COALESCE(SUM(p.amount),0)s FROM financial_payments p WHERE p.organization_id=:o AND p.active=1 AND p.movement_date>=date('now','start of month')",{o}).s);
    const toRecon=Number(get("SELECT COUNT(*) c FROM financial_payments WHERE organization_id=:o AND active=1 AND bank_account_id IS NOT NULL AND reconciled=0",{o}).c);
    const filters=`<form class="filters"><select name="type"><option value="">Pagar e receber</option><option value="PAYABLE" ${type==='PAYABLE'?'selected':''}>A pagar</option><option value="RECEIVABLE" ${type==='RECEIVABLE'?'selected':''}>A receber</option></select><input name="s" value="${C.esc(s)}" placeholder="Descrição, documento..."><button class="btn">Filtrar</button><a class="btn" href="/financeiro">Limpar</a></form>`;
    const actions=`${C.can(ctx,'finance','create')?'<a class="btn primary" href="/financeiro/novo">Novo lançamento</a>':''}${C.can(ctx,'finance','import')?'<a class="btn" href="/financeiro/importar">Importar</a>':''}<a class="btn" href="/conciliacao">Ir para conciliação</a>${C.can(ctx,'finance','export')?'<a class="btn" href="/relatorios/financeiro.csv">Exportar CSV</a>':''}`;
    const body=`<div class="grid">${U.card('A pagar em aberto',U.money(pendingPay))}${U.card('A receber em aberto',U.money(pendingRec))}${U.card('Baixas no mês',U.money(paidMonth))}${U.card('Baixas a conciliar',toRecon,'com conta bancária')}</div>`+U.panel('Contas a pagar e receber',filters+U.table(['Tipo','Descrição','Vencimento','Valor','Baixado','Última movimentação','Status','Ações'],tr));
    C.send(res,200,U.layout(ctx,'Financeiro',body,'/financeiro',{msg:q.msg,mt:q.mt,actions}));
  });

  function entryForm(ctx,e={},action='/financeiro'){
    const o=ctx.user.organization_id,cats=all('SELECT * FROM finance_categories WHERE organization_id=:o AND active=1 ORDER BY name',{o}).map(x=>[x.id,x.name]);
    const clients=all("SELECT id,COALESCE(NULLIF(trade_name,''),legal_name) name FROM clients WHERE organization_id=:o AND active=1 ORDER BY name",{o}).map(x=>[x.id,x.name]);
    const banks=bankOptions(o);const d=today();
    return `<form method="post" action="${action}">${U.csrf(ctx)}${U.formGrid(
      U.select('entry_type','Tipo',e.entry_type||'PAYABLE',entryTypes,{blank:false})+U.input('description','Descrição',e.description||'',{required:true})+
      U.select('category_id','Categoria',e.category_id||'',cats)+U.select('client_id','Cliente relacionado',e.client_id||'',clients)+
      U.input('supplier_name','Fornecedor / favorecido',e.supplier_name||'')+U.input('document_number','Documento / NF',e.document_number||'')+
      U.input('issue_date','Emissão',e.issue_date||d,{type:'date'})+U.input('due_date','Vencimento',e.due_date||d,{type:'date',required:true})+
      U.input('competence_date','Competência',e.competence_date||d,{type:'date'})+U.input('amount','Valor',e.amount??0,{type:'number',step:'0.01',min:0,required:true})+
      U.select('bank_account_id','Conta bancária prevista',e.bank_account_id||'',banks)+U.input('payment_method','Forma prevista de pagamento',e.payment_method||'')+
      U.textarea('notes','Observações',e.notes||''),`<a class="btn" href="/financeiro">Cancelar</a><button class="btn primary">Salvar lançamento</button>`)}</form>`;
  }
  r.get('/financeiro/novo',async(req,res,ctx)=>{if(!C.requirePerm(ctx,res,'finance','create'))return;C.send(res,200,U.layout(ctx,'Novo lançamento',U.panel('Conta a pagar / receber',entryForm(ctx)),'/financeiro'));});
  r.post('/financeiro',async(req,res,ctx)=>{if(!C.requirePerm(ctx,res,'finance','create'))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));if(!b.description||!b.due_date||C.num(b.amount)<=0)return C.redirect(res,C.flashUrl('/financeiro/novo','Descrição, vencimento e valor são obrigatórios.','err'));const fid=id(),t=now();run(`INSERT INTO financial_entries(id,organization_id,entry_type,description,category_id,client_id,supplier_name,document_number,issue_date,due_date,competence_date,amount,paid_amount,status,payment_method,bank_account_id,notes,imported,created_by,created_at,updated_at) VALUES(:id,:o,:type,:d,:cat,:cl,:sup,:doc,:issue,:due,:comp,:amt,0,'PENDING',:pm,:bank,:notes,0,:u,:t,:t)`,{id:fid,o:ctx.user.organization_id,type:b.entry_type==='RECEIVABLE'?'RECEIVABLE':'PAYABLE',d:String(b.description).trim(),cat:b.category_id||null,cl:b.client_id||null,sup:b.supplier_name||'',doc:b.document_number||'',issue:b.issue_date||null,due:b.due_date,comp:b.competence_date||null,amt:C.num(b.amount),pm:b.payment_method||'',bank:b.bank_account_id||null,notes:b.notes||'',u:ctx.user.id,t});C.audit(ctx,req,'CREATE','financial_entries',fid,null,{description:b.description,amount:C.num(b.amount),due_date:b.due_date});C.redirect(res,C.flashUrl(`/financeiro/${fid}/detalhes`,'Lançamento criado.'));});

  r.get('/financeiro/:id/detalhes',async(req,res,ctx,q,p)=>{if(!C.requirePerm(ctx,res,'finance'))return;const o=ctx.user.organization_id,e=get(`SELECT f.*,fc.name category_name,cl.trade_name,cl.legal_name FROM financial_entries f LEFT JOIN finance_categories fc ON fc.id=f.category_id LEFT JOIN clients cl ON cl.id=f.client_id WHERE f.id=:id AND f.organization_id=:o`,{id:p.id,o});if(!e)return C.send(res,404,C.errorPage('Lançamento não encontrado',''));const [sl,sc]=entryStat(e);const pays=all(`SELECT p.*,ba.name bank_name,bt.description bank_tx_desc,bt.tx_date bank_tx_date FROM financial_payments p LEFT JOIN bank_accounts ba ON ba.id=p.bank_account_id LEFT JOIN bank_transactions bt ON bt.id=p.bank_transaction_id WHERE p.organization_id=:o AND p.financial_entry_id=:e ORDER BY p.movement_date DESC,p.created_at DESC`,{o,e:e.id}).map(x=>`<tr><td>${U.dateBR(x.movement_date)}</td><td>${U.money(x.amount)}</td><td>${C.esc(x.bank_name||'Sem banco')}</td><td>${C.esc(x.payment_method||'-')}</td><td>${x.active?(x.reconciled?U.badge('Conciliada','ok'):U.badge('A conciliar','warn')):U.badge('Estornada','muted')}</td><td>${x.bank_transaction_id?`${U.dateBR(x.bank_tx_date)} · ${C.esc(x.bank_tx_desc||'Extrato')}`:'-'}</td><td>${x.active&&C.isAdmin(ctx)?`<form method="post" action="/financeiro/baixas/${x.id}/estornar">${U.csrf(ctx)}<button class="btn sm danger" data-confirm="Estornar esta baixa? O lançamento financeiro será recalculado e o vínculo bancário será removido.">Estornar</button></form>`:''}</td></tr>`);const remaining=Math.max(0,Number(e.amount)-Number(e.paid_amount));const body=`<div class="grid">${U.card('Tipo',e.entry_type==='PAYABLE'?'Conta a pagar':'Conta a receber')}${U.card('Valor',U.money(e.amount))}${U.card('Baixado',U.money(e.paid_amount))}${U.card('Saldo',U.money(remaining))}${U.card('Status',U.badge(sl,sc))}</div><div class="detail-grid"><div class="detail"><small>Vencimento</small><b>${U.dateBR(e.due_date)}</b></div><div class="detail"><small>Documento</small><b>${C.esc(e.document_number||'-')}</b></div><div class="detail"><small>Categoria / parte</small><b>${C.esc(e.category_name||e.supplier_name||e.trade_name||e.legal_name||'-')}</b></div></div>`+U.panel('Histórico de baixas / recebimentos',U.table(['Data movimento','Valor','Banco','Forma','Conciliação','Extrato vinculado','Ações'],pays));const actions=`<a class="btn" href="/financeiro">← Financeiro</a>${C.can(ctx,'finance','edit')?`<a class="btn" href="/financeiro/${e.id}/editar">Editar</a>${remaining>0&&e.status!=='CANCELLED'?`<a class="btn primary" href="/financeiro/${e.id}/baixar">Nova baixa</a>`:''}`:''}${C.isAdmin(ctx)?`<form method="post" action="/financeiro/${e.id}/excluir">${U.csrf(ctx)}<button class="btn danger" data-confirm="Excluir definitivamente este lançamento?">Excluir</button></form>`:''}`;C.send(res,200,U.layout(ctx,e.description,body,'/financeiro',{msg:q.msg,mt:q.mt,actions}));});

  r.get('/financeiro/:id/editar',async(req,res,ctx,q,p)=>{if(!C.requirePerm(ctx,res,'finance','edit'))return;const e=get('SELECT * FROM financial_entries WHERE id=:id AND organization_id=:o',{id:p.id,o:ctx.user.organization_id});if(!e)return C.send(res,404,C.errorPage('Lançamento não encontrado',''));C.send(res,200,U.layout(ctx,'Editar lançamento',U.panel(e.description,entryForm(ctx,e,`/financeiro/${e.id}/editar`)),'/financeiro',{msg:q.msg,mt:q.mt}));});
  r.post('/financeiro/:id/editar',async(req,res,ctx,q,p)=>{if(!C.requirePerm(ctx,res,'finance','edit'))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,e=get('SELECT * FROM financial_entries WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!e)return C.send(res,404,C.errorPage('Lançamento não encontrado',''));const amount=C.num(b.amount);const paid=Number(get('SELECT COALESCE(SUM(amount),0)s FROM financial_payments WHERE organization_id=:o AND financial_entry_id=:e AND active=1',{o,e:e.id}).s);if(amount<=0||amount<paid-0.005)return C.redirect(res,C.flashUrl(`/financeiro/${e.id}/editar`,`O valor não pode ser menor que o total já baixado (${U.money(paid)}).`,'err'));run(`UPDATE financial_entries SET entry_type=:type,description=:d,category_id=:cat,client_id=:cl,supplier_name=:sup,document_number=:doc,issue_date=:issue,due_date=:due,competence_date=:comp,amount=:amt,payment_method=:pm,notes=:notes,updated_at=:t WHERE id=:id AND organization_id=:o`,{type:b.entry_type==='RECEIVABLE'?'RECEIVABLE':'PAYABLE',d:b.description||e.description,cat:b.category_id||null,cl:b.client_id||null,sup:b.supplier_name||'',doc:b.document_number||'',issue:b.issue_date||null,due:b.due_date||e.due_date,comp:b.competence_date||null,amt:amount,pm:b.payment_method||'',notes:b.notes||'',t:now(),id:e.id,o});recalcEntry(o,e.id);C.audit(ctx,req,'UPDATE','financial_entries',e.id,e,{description:b.description,amount,due_date:b.due_date});C.redirect(res,C.flashUrl(`/financeiro/${e.id}/detalhes`,'Lançamento atualizado.'));});

  r.get('/financeiro/:id/baixar',async(req,res,ctx,q,p)=>{if(!C.requirePerm(ctx,res,'finance','edit'))return;const o=ctx.user.organization_id,e=get('SELECT * FROM financial_entries WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!e)return C.send(res,404,C.errorPage('Lançamento não encontrado',''));if(e.status==='CANCELLED')return C.redirect(res,C.flashUrl(`/financeiro/${e.id}/detalhes`,'Lançamento cancelado não pode receber baixa.','warn'));const remaining=Math.max(0,Number(e.amount)-Number(e.paid_amount));if(remaining<0.005)return C.redirect(res,C.flashUrl(`/financeiro/${e.id}/detalhes`,'Este lançamento já está totalmente baixado.','warn'));const banks=bankOptions(o);if(!banks.length){const warn=`<div class="alert warn"><b>Nenhuma conta bancária ativa.</b> Para registrar uma baixa com data e banco — e fazê-la aparecer na conciliação — cadastre primeiro uma conta bancária.</div><p><a class="btn primary" href="/conciliacao/conta/nova?return=${encodeURIComponent('/financeiro/'+e.id+'/baixar')}">Cadastrar conta bancária</a> <a class="btn" href="/financeiro/${e.id}/detalhes">Voltar</a></p>`;return C.send(res,200,U.layout(ctx,'Baixar lançamento',U.panel(e.description,warn),'/financeiro'));}const f=`<div class="alert ok">Esta baixa aparecerá automaticamente na <b>Conciliação Bancária</b> pela data e conta escolhidas. Depois você poderá vinculá-la ao movimento real do extrato.</div><form method="post" action="/financeiro/${e.id}/baixar">${U.csrf(ctx)}${U.formGrid(U.input('movement_date','Data do movimento',today(),{type:'date',required:true})+U.input('amount','Valor da baixa',remaining.toFixed(2),{type:'number',step:'0.01',min:0.01,required:true})+U.select('bank_account_id','Conta bancária',e.bank_account_id||'',banks,{required:true})+U.input('payment_method','Forma de pagamento / recebimento',e.payment_method||'')+U.input('document_number','Documento / comprovante',e.document_number||'')+U.textarea('notes','Observações',''),`<a class="btn" href="/financeiro/${e.id}/detalhes">Cancelar</a><button class="btn primary">Confirmar baixa</button>`)}</form>`;C.send(res,200,U.layout(ctx,e.entry_type==='PAYABLE'?'Baixar pagamento':'Baixar recebimento',U.panel(`${e.description} · saldo ${U.money(remaining)}`,f),'/financeiro',{msg:q.msg,mt:q.mt}));});
  r.post('/financeiro/:id/baixar',async(req,res,ctx,q,p)=>{if(!C.requirePerm(ctx,res,'finance','edit'))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,e=get('SELECT * FROM financial_entries WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!e)return C.send(res,404,C.errorPage('Lançamento não encontrado',''));const bank=get('SELECT * FROM bank_accounts WHERE id=:id AND organization_id=:o AND active=1',{id:b.bank_account_id,o});const amount=C.num(b.amount),remaining=Math.max(0,Number(e.amount)-Number(e.paid_amount)),d=C.normDate(b.movement_date);if(!bank)return C.redirect(res,C.flashUrl(`/financeiro/${e.id}/baixar`,'Selecione uma conta bancária ativa.','err'));if(!d||amount<=0||amount>remaining+0.005)return C.redirect(res,C.flashUrl(`/financeiro/${e.id}/baixar`,`Informe uma data válida e valor entre R$ 0,01 e ${U.money(remaining)}.`,'err'));const pid=id(),t=now();transaction(()=>{run(`INSERT INTO financial_payments(id,organization_id,financial_entry_id,movement_date,amount,bank_account_id,payment_method,document_number,notes,active,reconciled,source,created_by,created_at,updated_at) VALUES(:id,:o,:e,:d,:a,:b,:pm,:doc,:notes,1,0,'FINANCE',:u,:t,:t)`,{id:pid,o,e:e.id,d,a:amount,b:bank.id,pm:b.payment_method||'',doc:b.document_number||'',notes:b.notes||'',u:ctx.user.id,t});recalcEntry(o,e.id);});C.audit(ctx,req,'PAYMENT','financial_payments',pid,null,{financial_entry_id:e.id,movement_date:d,amount,bank:bank.name});C.redirect(res,C.flashUrl(`/financeiro/${e.id}/detalhes`,'Baixa registrada e enviada para a conciliação bancária.'));});
  // compatibilidade com botão de versões antigas
  r.post('/financeiro/:id/pagar',async(req,res,ctx,q,p)=>{if(!C.requirePerm(ctx,res,'finance','edit'))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));C.redirect(res,C.flashUrl(`/financeiro/${p.id}/baixar`,'Agora a baixa exige data e conta bancária para alimentar corretamente a conciliação.','warn'));});

  r.post('/financeiro/baixas/:id/estornar',async(req,res,ctx,q,p)=>{if(!C.requireAdmin(ctx,res))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,pay=get('SELECT * FROM financial_payments WHERE id=:id AND organization_id=:o AND active=1',{id:p.id,o});if(!pay)return C.redirect(res,'/financeiro');transaction(()=>{if(pay.bank_transaction_id)run('UPDATE bank_transactions SET reconciled=0,financial_payment_id=NULL,financial_entry_id=NULL,updated_at=:t WHERE id=:id AND organization_id=:o',{t:now(),id:pay.bank_transaction_id,o});run('UPDATE financial_payments SET active=0,reconciled=0,bank_transaction_id=NULL,reversed_by=:u,reversed_at=:t,reversal_reason=:r,updated_at=:t WHERE id=:id AND organization_id=:o',{u:ctx.user.id,t:now(),r:String(b.reason||'Estorno administrativo'),id:pay.id,o});recalcEntry(o,pay.financial_entry_id);});C.audit(ctx,req,'REVERSE_PAYMENT','financial_payments',pay.id,pay,{active:0});C.redirect(res,C.flashUrl(`/financeiro/${pay.financial_entry_id}/detalhes`,'Baixa estornada.'));});

  r.post('/financeiro/:id/cancelar',async(req,res,ctx,q,p)=>{if(!C.requirePerm(ctx,res,'finance','edit'))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,e=get('SELECT * FROM financial_entries WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!e)return C.redirect(res,'/financeiro');if(Number(e.paid_amount)>0)return C.redirect(res,C.flashUrl(`/financeiro/${e.id}/detalhes`,'Não é possível cancelar um lançamento com baixas. Estorne as baixas primeiro (ADMIN).','warn'));run("UPDATE financial_entries SET status='CANCELLED',updated_at=:t WHERE id=:id AND organization_id=:o",{t:now(),id:e.id,o});C.audit(ctx,req,'CANCEL','financial_entries',e.id,e,{status:'CANCELLED'});C.redirect(res,C.flashUrl(`/financeiro/${e.id}/detalhes`,'Lançamento cancelado.'));});
  r.post('/financeiro/:id/excluir',async(req,res,ctx,q,p)=>{if(!C.requireAdmin(ctx,res))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,e=get('SELECT * FROM financial_entries WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!e)return C.redirect(res,'/financeiro');const deps=Number(get('SELECT COUNT(*) c FROM financial_payments WHERE financial_entry_id=:id AND organization_id=:o',{id:e.id,o}).c)+Number(get('SELECT COUNT(*) c FROM bank_transactions WHERE financial_entry_id=:id AND organization_id=:o',{id:e.id,o}).c);if(deps)return C.redirect(res,C.flashUrl(`/financeiro/${e.id}/detalhes`,'Este lançamento possui histórico de baixa/conciliação e não pode ser excluído definitivamente. Use cancelamento ou estorno para preservar a auditoria.','warn'));run('DELETE FROM financial_entries WHERE id=:id AND organization_id=:o',{id:e.id,o});C.audit(ctx,req,'DELETE','financial_entries',e.id,e,null);C.redirect(res,C.flashUrl('/financeiro','Lançamento excluído definitivamente.'));});

  r.get('/financeiro/importar',async(req,res,ctx,q)=>{if(!C.requirePerm(ctx,res,'finance','import'))return;const example=`tipo;descricao;vencimento;valor;documento;fornecedor\nPAYABLE;Energia elétrica;2026-08-20;850,40;NF123;Fornecedor XPTO\nRECEIVABLE;Contrato Cliente A;2026-08-10;15000,00;FAT100;`;const f=`<div class="panel-body"><p>Importe <b>XLSX</b> ou <b>CSV</b>. Colunas reconhecidas: <code>tipo</code>, <code>descricao</code>, <code>vencimento</code>, <code>valor</code>, <code>documento</code>, <code>fornecedor</code>, <code>emissao</code>, <code>competencia</code>.</p><pre class="code">${C.esc(example)}</pre></div><form method="post" enctype="multipart/form-data" action="/financeiro/importar">${U.csrf(ctx)}${U.formGrid(`<label class="field span2"><span>Arquivo XLSX ou CSV <span class="field-help-icon" title="Use a planilha-modelo exibida acima e mantenha uma linha por lançamento financeiro.">?</span></span><input type="file" name="file" accept=".xlsx,.csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/csv" required><small class="field-help"><span class="help-dot">i</span>Use a planilha-modelo exibida acima. Cada linha deve representar um lançamento a pagar ou a receber.</small></label>`,`<a class="btn" href="/financeiro">Voltar</a><button class="btn primary">Importar lançamentos</button>`)}</form>`;C.send(res,200,U.layout(ctx,'Importação financeira',U.panel('Importar planilha',f),'/financeiro',{msg:q.msg,mt:q.mt}));});
  r.post('/financeiro/importar',async(req,res,ctx)=>{if(!C.requirePerm(ctx,res,'finance','import'))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));if(!b.file?.data)return C.redirect(res,C.flashUrl('/financeiro/importar','Selecione um arquivo.','err'));const rows=String(b.file.filename||'').toLowerCase().endsWith('.xlsx')?C.parseXLSX(b.file.data):C.parseCSV(b.file.data.toString('utf8')),batch='FIN-'+Date.now();let count=0;transaction(()=>{for(const x of rows){const desc=x.descricao||x.description,due=C.normDate(x.vencimento||x.due_date),amt=C.num(x.valor||x.amount);if(!desc||!due||amt<=0)continue;const fid=id(),t=now();run(`INSERT INTO financial_entries(id,organization_id,entry_type,description,supplier_name,document_number,issue_date,due_date,competence_date,amount,paid_amount,status,notes,imported,import_batch,created_by,created_at,updated_at) VALUES(:id,:o,:type,:d,:sup,:doc,:issue,:due,:comp,:amt,0,'PENDING','Importado de planilha',1,:batch,:u,:t,:t)`,{id:fid,o:ctx.user.organization_id,type:String(x.tipo||x.entry_type||'PAYABLE').toUpperCase().includes('REC')?'RECEIVABLE':'PAYABLE',d:desc,sup:x.fornecedor||x.supplier||'',doc:x.documento||x.document_number||'',issue:C.normDate(x.emissao)||null,due,comp:C.normDate(x.competencia)||null,amt,batch,u:ctx.user.id,t});count++;}});C.audit(ctx,req,'IMPORT','financial_entries',batch,null,{rows:count,batch});C.redirect(res,C.flashUrl('/financeiro',`${count} lançamento(s) importado(s).`));});

  // ---------------- CONTAS BANCÁRIAS ----------------
  r.get('/conciliacao/contas',async(req,res,ctx,q)=>{if(!C.requirePerm(ctx,res,'reconciliation'))return;const o=ctx.user.organization_id,banks=all('SELECT * FROM bank_accounts WHERE organization_id=:o ORDER BY active DESC,name',{o});const rows=banks.map(b=>{const tx=Number(get('SELECT COUNT(*) c FROM bank_transactions WHERE bank_account_id=:id AND organization_id=:o',{id:b.id,o}).c),pm=Number(get('SELECT COUNT(*) c FROM financial_payments WHERE bank_account_id=:id AND organization_id=:o',{id:b.id,o}).c);return `<tr><td><b>${C.esc(b.name)}</b><br><small>${C.esc(b.bank_name||'')}</small></td><td>${C.esc(b.agency||'-')}</td><td>${C.esc(b.account_number||'-')}</td><td>${U.money(b.opening_balance)}</td><td>${b.active?U.badge('Ativa','ok'):U.badge('Inativa','muted')}</td><td>${tx} extrato(s) · ${pm} baixa(s)</td><td><div class="row-actions"><a class="btn sm" href="/conciliacao?bank=${b.id}">Abrir</a>${C.can(ctx,'reconciliation','edit')?`<a class="btn sm" href="/conciliacao/contas/${b.id}/editar">Editar</a><form method="post" action="/conciliacao/contas/${b.id}/toggle">${U.csrf(ctx)}<button class="btn sm">${b.active?'Inativar':'Reativar'}</button></form>`:''}${C.isAdmin(ctx)?`<form method="post" action="/conciliacao/contas/${b.id}/excluir">${U.csrf(ctx)}<button class="btn sm danger" data-confirm="Excluir esta conta bancária definitivamente? Só será permitido se ela não tiver histórico.">Excluir</button></form>`:''}</div></td></tr>`});C.send(res,200,U.layout(ctx,'Contas bancárias',U.panel('Cadastro e manutenção',U.table(['Conta','Agência','Número','Saldo inicial','Status','Histórico','Ações'],rows)),'/conciliacao',{msg:q.msg,mt:q.mt,actions:`<a class="btn" href="/conciliacao">← Conciliação</a>${C.can(ctx,'reconciliation','create')?'<a class="btn primary" href="/conciliacao/conta/nova">Nova conta</a>':''}`}));});
  function bankForm(ctx,b={},action='/conciliacao/contas',back='/conciliacao/contas',returnTo=''){const ret=String(returnTo||'').startsWith('/')?String(returnTo):'';return `<form method="post" action="${action}">${U.csrf(ctx)}${ret?`<input type="hidden" name="return_to" value="${C.esc(ret)}">`:''}${U.formGrid(U.input('name','Nome para identificação',b.name||'Conta principal',{required:true})+U.input('bank_name','Banco',b.bank_name||'')+U.input('agency','Agência',b.agency||'')+U.input('account_number','Conta',b.account_number||'')+U.input('pix_key','Chave PIX',b.pix_key||'')+U.input('opening_balance','Saldo inicial',b.opening_balance??0,{type:'number',step:'0.01'})+U.textarea('notes','Observações',b.notes||''),`<a class="btn" href="${C.esc(back)}">Cancelar</a><button class="btn primary">Salvar conta</button>`)}</form>`;}
  r.get('/conciliacao/conta/nova',async(req,res,ctx,q)=>{if(!C.requirePerm(ctx,res,'reconciliation','create'))return;C.send(res,200,U.layout(ctx,'Nova conta bancária',U.panel('Conta',bankForm(ctx,{},'/conciliacao/contas',q.return||'/conciliacao/contas',q.return||'')),'/conciliacao'));});
  r.post('/conciliacao/contas',async(req,res,ctx)=>{if(!C.requirePerm(ctx,res,'reconciliation','create'))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));if(!String(b.name||'').trim())return C.redirect(res,C.flashUrl('/conciliacao/conta/nova','Nome da conta é obrigatório.','err'));const bid=id(),t=now();run(`INSERT INTO bank_accounts(id,organization_id,name,bank_name,agency,account_number,pix_key,opening_balance,active,notes,created_at,updated_at) VALUES(:id,:o,:n,:bank,:ag,:ac,:pix,:bal,1,:notes,:t,:t)`,{id:bid,o:ctx.user.organization_id,n:String(b.name).trim(),bank:b.bank_name||'',ag:b.agency||'',ac:b.account_number||'',pix:b.pix_key||'',bal:C.num(b.opening_balance),notes:b.notes||'',t});C.audit(ctx,req,'CREATE','bank_accounts',bid,null,{name:b.name});const ret=String(b.return_to||'').startsWith('/')?String(b.return_to):`/conciliacao?bank=${bid}`;C.redirect(res,C.flashUrl(ret,'Conta bancária criada.'));});
  r.get('/conciliacao/contas/:id/editar',async(req,res,ctx,q,p)=>{if(!C.requirePerm(ctx,res,'reconciliation','edit'))return;const b=get('SELECT * FROM bank_accounts WHERE id=:id AND organization_id=:o',{id:p.id,o:ctx.user.organization_id});if(!b)return C.send(res,404,C.errorPage('Conta não encontrada',''));C.send(res,200,U.layout(ctx,'Editar conta bancária',U.panel(b.name,bankForm(ctx,b,`/conciliacao/contas/${b.id}`)),'/conciliacao',{msg:q.msg,mt:q.mt}));});
  r.post('/conciliacao/contas/:id',async(req,res,ctx,q,p)=>{if(!C.requirePerm(ctx,res,'reconciliation','edit'))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,old=get('SELECT * FROM bank_accounts WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!old)return C.send(res,404,C.errorPage('Conta não encontrada',''));run(`UPDATE bank_accounts SET name=:n,bank_name=:bank,agency=:ag,account_number=:ac,pix_key=:pix,opening_balance=:bal,notes=:notes,updated_at=:t WHERE id=:id AND organization_id=:o`,{n:String(b.name||old.name).trim(),bank:b.bank_name||'',ag:b.agency||'',ac:b.account_number||'',pix:b.pix_key||'',bal:C.num(b.opening_balance),notes:b.notes||'',t:now(),id:old.id,o});C.audit(ctx,req,'UPDATE','bank_accounts',old.id,old,{name:b.name,bank_name:b.bank_name,account_number:b.account_number});C.redirect(res,C.flashUrl(`/conciliacao?bank=${old.id}`,'Conta bancária atualizada.'));});
  r.post('/conciliacao/contas/:id/toggle',async(req,res,ctx,q,p)=>{if(!C.requirePerm(ctx,res,'reconciliation','edit'))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,old=get('SELECT * FROM bank_accounts WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!old)return C.redirect(res,'/conciliacao/contas');run('UPDATE bank_accounts SET active=:a,updated_at=:t WHERE id=:id AND organization_id=:o',{a:old.active?0:1,t:now(),id:old.id,o});C.audit(ctx,req,old.active?'DEACTIVATE':'ACTIVATE','bank_accounts',old.id,{active:old.active},{active:old.active?0:1});C.redirect(res,C.flashUrl('/conciliacao/contas','Situação da conta alterada.'));});
  r.post('/conciliacao/contas/:id/excluir',async(req,res,ctx,q,p)=>{if(!C.requireAdmin(ctx,res))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,old=get('SELECT * FROM bank_accounts WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!old)return C.redirect(res,'/conciliacao/contas');const deps=Number(get('SELECT COUNT(*) c FROM bank_transactions WHERE bank_account_id=:id AND organization_id=:o',{id:old.id,o}).c)+Number(get('SELECT COUNT(*) c FROM financial_payments WHERE bank_account_id=:id AND organization_id=:o',{id:old.id,o}).c)+Number(get('SELECT COUNT(*) c FROM financial_entries WHERE bank_account_id=:id AND organization_id=:o',{id:old.id,o}).c);if(deps)return C.redirect(res,C.flashUrl('/conciliacao/contas','Conta não excluída porque possui histórico. Inative-a para preservar os registros.','warn'));run('DELETE FROM bank_accounts WHERE id=:id AND organization_id=:o',{id:old.id,o});C.audit(ctx,req,'DELETE','bank_accounts',old.id,old,null);C.redirect(res,C.flashUrl('/conciliacao/contas','Conta bancária excluída definitivamente.'));});

  // ---------------- CONCILIAÇÃO ----------------
  r.get('/conciliacao',async(req,res,ctx,q)=>{
    if(!C.requirePerm(ctx,res,'reconciliation'))return;
    const o=ctx.user.organization_id,banks=all('SELECT * FROM bank_accounts WHERE organization_id=:o ORDER BY active DESC,name',{o});
    if(!banks.length){const body=`<div class="alert warn"><b>Você ainda não possui contas bancárias.</b> Cadastre uma conta para registrar baixas por banco, importar extrato e fazer conciliações.</div>`;return C.send(res,200,U.layout(ctx,'Conciliação bancária',U.panel('Primeiro passo',body),'/conciliacao',{actions:C.can(ctx,'reconciliation','create')?'<a class="btn primary" href="/conciliacao/conta/nova">Criar conta bancária</a>':''}));}
    const bankId=String(q.bank||banks[0].id),bank=get('SELECT * FROM bank_accounts WHERE id=:id AND organization_id=:o',{id:bankId,o})||banks[0];
    const rg=range(q),show=String(q.show||'all');
    const txs=all(`SELECT bt.*,fe.description financial_description,fe.entry_type FROM bank_transactions bt LEFT JOIN financial_entries fe ON fe.id=bt.financial_entry_id WHERE bt.organization_id=:o AND bt.bank_account_id=:b AND bt.tx_date BETWEEN :f AND :t ORDER BY bt.tx_date DESC,bt.created_at DESC LIMIT 2000`,{o,b:bank.id,f:rg.from,t:rg.to}).filter(x=>show==='pending'?!x.reconciled:show==='reconciled'?!!x.reconciled:true);
    const pays=all(`SELECT p.*,fe.description,fe.entry_type,fe.document_number,ba.name bank_name FROM financial_payments p JOIN financial_entries fe ON fe.id=p.financial_entry_id LEFT JOIN bank_accounts ba ON ba.id=p.bank_account_id WHERE p.organization_id=:o AND p.bank_account_id=:b AND p.active=1 AND p.movement_date BETWEEN :f AND :t ORDER BY p.movement_date DESC,p.created_at DESC LIMIT 2000`,{o,b:bank.id,f:rg.from,t:rg.to});
    const txRows=txs.map(t=>`<tr><td>${U.dateBR(t.tx_date)}</td><td>${U.badge(txOrigin(t),t.imported?'info':'muted')}</td><td><b>${C.esc(t.description)}</b><br><small>${C.esc(t.document_number||'')}</small></td><td class="right ${Number(t.amount)<0?'danger-text':''}">${U.money(t.amount)}</td><td>${t.financial_description?`<b>${C.esc(t.financial_description)}</b>`:'-'}</td><td>${t.reconciled?U.badge('Conciliado','ok'):U.badge('Pendente','warn')}</td><td><div class="row-actions">${!t.reconciled&&C.can(ctx,'reconciliation','edit')?`<a class="btn sm primary" href="/conciliacao/${t.id}/vincular">Vincular</a><a class="btn sm" href="/conciliacao/movimentos/${t.id}/editar">Editar</a>`:''}${t.reconciled&&C.isAdmin(ctx)?`<form method="post" action="/conciliacao/${t.id}/desvincular">${U.csrf(ctx)}<button class="btn sm">Desvincular</button></form>`:''}${C.isAdmin(ctx)?`<form method="post" action="/conciliacao/movimentos/${t.id}/excluir">${U.csrf(ctx)}<button class="btn sm danger" data-confirm="Excluir esta linha do extrato? Só é permitido quando ela não está conciliada.">Excluir</button></form>`:''}</div></td></tr>`);
    const payRows=pays.map(p=>`<tr><td>${U.dateBR(p.movement_date)}</td><td>${U.badge(p.entry_type==='PAYABLE'?'Pagamento':'Recebimento',p.entry_type==='PAYABLE'?'warn':'info')}</td><td><a href="/financeiro/${p.financial_entry_id}/detalhes"><b>${C.esc(p.description)}</b></a><br><small>${C.esc(p.document_number||'')}</small></td><td class="right">${U.money(p.amount)}</td><td>${p.reconciled?U.badge('Conciliada','ok'):U.badge('Aguardando extrato','warn')}</td><td>${p.bank_transaction_id?'Vinculada ao extrato':'-'}</td></tr>`);
    const map=new Map();const day=d=>{if(!map.has(d))map.set(d,{date:d,credit:0,debit:0,rec:0,pay:0,txPending:0,payPending:0});return map.get(d)};for(const t of all(`SELECT * FROM bank_transactions WHERE organization_id=:o AND bank_account_id=:b AND tx_date BETWEEN :f AND :t`,{o,b:bank.id,f:rg.from,t:rg.to})){const x=day(t.tx_date);if(Number(t.amount)>=0)x.credit+=Number(t.amount);else x.debit+=Math.abs(Number(t.amount));if(!t.reconciled)x.txPending++;}for(const p of pays){const x=day(p.movement_date);if(p.entry_type==='RECEIVABLE')x.rec+=Number(p.amount);else x.pay+=Number(p.amount);if(!p.reconciled)x.payPending++;}
    const daily=[...map.values()].sort((a,b)=>b.date.localeCompare(a.date)).map(d=>`<tr><td><b>${U.dateBR(d.date)}</b></td><td class="right">${U.money(d.credit)}</td><td class="right">${U.money(d.debit)}</td><td class="right">${U.money(d.rec)}</td><td class="right">${U.money(d.pay)}</td><td>${d.txPending?U.badge(`${d.txPending} extrato(s)`,'warn'):U.badge('Extrato OK','ok')}</td><td>${d.payPending?U.badge(`${d.payPending} baixa(s)`,'warn'):U.badge('Financeiro OK','ok')}</td></tr>`);
    const allTxPeriod=all(`SELECT * FROM bank_transactions WHERE organization_id=:o AND bank_account_id=:b AND tx_date BETWEEN :f AND :t`,{o,b:bank.id,f:rg.from,t:rg.to});const credit=allTxPeriod.filter(x=>Number(x.amount)>=0).reduce((a,x)=>a+Number(x.amount),0),debit=allTxPeriod.filter(x=>Number(x.amount)<0).reduce((a,x)=>a+Math.abs(Number(x.amount)),0);const balance=Number(bank.opening_balance||0)+Number(get('SELECT COALESCE(SUM(amount),0)s FROM bank_transactions WHERE organization_id=:o AND bank_account_id=:b AND tx_date<=:d',{o,b:bank.id,d:rg.to}).s);const pendingTx=Number(get('SELECT COUNT(*) c FROM bank_transactions WHERE organization_id=:o AND bank_account_id=:b AND reconciled=0',{o,b:bank.id}).c),pendingPay=Number(get('SELECT COUNT(*) c FROM financial_payments WHERE organization_id=:o AND bank_account_id=:b AND active=1 AND reconciled=0',{o,b:bank.id}).c);
    const opts=banks.map(b=>`<option value="${b.id}" ${b.id===bank.id?'selected':''}>${C.esc(b.name)}${b.active?'':' · INATIVA'} · ${C.esc(b.bank_name||'')}</option>`).join('');const filters=`<form class="filters"><select name="bank">${opts}</select><label>De <input type="date" name="from" value="${rg.from}"></label><label>Até <input type="date" name="to" value="${rg.to}"></label><select name="show"><option value="all" ${show==='all'?'selected':''}>Todos extratos</option><option value="pending" ${show==='pending'?'selected':''}>Só pendentes</option><option value="reconciled" ${show==='reconciled'?'selected':''}>Só conciliados</option></select><button class="btn">Aplicar</button><a class="btn" href="/conciliacao?bank=${bank.id}">Mês atual</a></form>`;
    const accountActions=`<div class="row-actions"><a class="btn" href="/conciliacao/contas">Gerenciar contas</a>${C.can(ctx,'reconciliation','edit')?`<a class="btn" href="/conciliacao/contas/${bank.id}/editar">Editar esta conta</a>`:''}${C.can(ctx,'reconciliation','create')?'<a class="btn" href="/conciliacao/movimento/novo">Lançar extrato manual</a>':''}${C.can(ctx,'reconciliation','import')?'<a class="btn" href="/conciliacao/importar">Importar extrato</a>':''}${C.can(ctx,'reconciliation','approve')?`<form method="post" action="/conciliacao/auto">${U.csrf(ctx)}<input type="hidden" name="bank_id" value="${bank.id}"><input type="hidden" name="from" value="${rg.from}"><input type="hidden" name="to" value="${rg.to}"><button class="btn primary">Conciliar automaticamente</button></form>`:''}</div>`;
    const body=`<div class="alert ok"><b>Como funciona:</b> a tabela “Baixas do financeiro” mostra pagamentos/recebimentos que você registrou no módulo Financeiro. A tabela “Extrato bancário” mostra o que veio do banco. Use “Vincular” para fazer os dois baterem.</div><div class="grid">${U.card('Conta',C.esc(bank.name),C.esc(bank.bank_name||''))}${U.card('Saldo até '+U.dateBR(rg.to),U.money(balance))}${U.card('Créditos no período',U.money(credit))}${U.card('Débitos no período',U.money(debit))}${U.card('Extratos pendentes',pendingTx)}${U.card('Baixas pendentes',pendingPay)}</div>`+U.panel('Período e conta',filters,accountActions)+U.panel('Conciliação por dia',U.table(['Data','Extrato entradas','Extrato saídas','Financeiro recebimentos','Financeiro pagamentos','Pendências extrato','Pendências financeiro'],daily))+`<div class="grid2">${U.panel('Extrato bancário',U.table(['Data','Origem','Descrição','Valor','Financeiro vinculado','Situação','Ações'],txRows))}${U.panel('Baixas do financeiro',U.table(['Data movimento','Tipo','Lançamento','Valor','Situação','Vínculo'],payRows))}</div>`;
    C.send(res,200,U.layout(ctx,'Conciliação bancária',body,'/conciliacao',{msg:q.msg,mt:q.mt}));
  });

  r.get('/conciliacao/movimento/novo',async(req,res,ctx,q)=>{if(!C.requirePerm(ctx,res,'reconciliation','create'))return;const banks=bankOptions(ctx.user.organization_id);const f=`<form method="post" action="/conciliacao/movimentos">${U.csrf(ctx)}${U.formGrid(U.select('bank_account_id','Conta',q.bank||'',banks,{required:true})+U.input('tx_date','Data do extrato',today(),{type:'date',required:true})+U.input('description','Descrição','',{required:true})+U.input('amount','Valor (negativo = saída)',0,{type:'number',step:'0.01',required:true})+U.input('document_number','Documento','')+U.textarea('notes','Observações',''),`<a class="btn" href="/conciliacao">Cancelar</a><button class="btn primary">Lançar no extrato</button>`)}</form>`;C.send(res,200,U.layout(ctx,'Movimento bancário',U.panel('Lançamento manual do extrato',f),'/conciliacao'));});
  r.post('/conciliacao/movimentos',async(req,res,ctx)=>{if(!C.requirePerm(ctx,res,'reconciliation','create'))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,bank=get('SELECT * FROM bank_accounts WHERE id=:id AND organization_id=:o AND active=1',{id:b.bank_account_id,o}),d=C.normDate(b.tx_date),amount=C.num(b.amount);if(!bank||!d||!String(b.description||'').trim()||Math.abs(amount)<0.005)return C.redirect(res,C.flashUrl('/conciliacao/movimento/novo','Conta, data, descrição e valor diferente de zero são obrigatórios.','err'));const tid=id(),t=now();run(`INSERT INTO bank_transactions(id,organization_id,bank_account_id,tx_date,description,amount,document_number,imported,reconciled,movement_origin,notes,created_by,created_at,updated_at) VALUES(:id,:o,:b,:d,:desc,:amt,:doc,0,0,'STATEMENT',:notes,:u,:t,:t)`,{id:tid,o,b:bank.id,d,desc:String(b.description).trim(),amt:amount,doc:b.document_number||'',notes:b.notes||'',u:ctx.user.id,t});C.audit(ctx,req,'CREATE','bank_transactions',tid,null,{bank:bank.name,tx_date:d,amount});C.redirect(res,C.flashUrl(`/conciliacao?bank=${bank.id}&from=${d}&to=${d}`,'Movimento de extrato adicionado.'));});
  r.get('/conciliacao/movimentos/:id/editar',async(req,res,ctx,q,p)=>{if(!C.requirePerm(ctx,res,'reconciliation','edit'))return;const o=ctx.user.organization_id,t=get('SELECT * FROM bank_transactions WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!t)return C.send(res,404,C.errorPage('Movimento não encontrado',''));if(t.reconciled)return C.redirect(res,C.flashUrl(`/conciliacao?bank=${t.bank_account_id}`,'Desvincule o movimento antes de editá-lo.','warn'));const f=`<form method="post" action="/conciliacao/movimentos/${t.id}">${U.csrf(ctx)}${U.formGrid(U.select('bank_account_id','Conta',t.bank_account_id,bankOptions(o),{required:true})+U.input('tx_date','Data do extrato',t.tx_date,{type:'date',required:true})+U.input('description','Descrição',t.description,{required:true})+U.input('amount','Valor (negativo = saída)',t.amount,{type:'number',step:'0.01',required:true})+U.input('document_number','Documento',t.document_number||'')+U.textarea('notes','Observações',t.notes||''),`<a class="btn" href="/conciliacao?bank=${t.bank_account_id}">Cancelar</a><button class="btn primary">Salvar movimento</button>`)}</form>`;C.send(res,200,U.layout(ctx,'Editar movimento do extrato',U.panel(t.description,f),'/conciliacao',{msg:q.msg,mt:q.mt}));});
  r.post('/conciliacao/movimentos/:id',async(req,res,ctx,q,p)=>{if(!C.requirePerm(ctx,res,'reconciliation','edit'))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,t=get('SELECT * FROM bank_transactions WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!t)return C.send(res,404,C.errorPage('Movimento não encontrado',''));if(t.reconciled)return C.redirect(res,C.flashUrl(`/conciliacao?bank=${t.bank_account_id}`,'Desvincule antes de editar.','warn'));const bank=get('SELECT * FROM bank_accounts WHERE id=:id AND organization_id=:o',{id:b.bank_account_id,o}),d=C.normDate(b.tx_date),amount=C.num(b.amount);if(!bank||!d||Math.abs(amount)<0.005)return C.redirect(res,C.flashUrl(`/conciliacao/movimentos/${t.id}/editar`,'Dados inválidos.','err'));run(`UPDATE bank_transactions SET bank_account_id=:b,tx_date=:d,description=:desc,amount=:a,document_number=:doc,notes=:notes,updated_at=:t WHERE id=:id AND organization_id=:o`,{b:bank.id,d,desc:String(b.description||t.description).trim(),a:amount,doc:b.document_number||'',notes:b.notes||'',t:now(),id:t.id,o});C.audit(ctx,req,'UPDATE','bank_transactions',t.id,t,{bank_account_id:bank.id,tx_date:d,amount});C.redirect(res,C.flashUrl(`/conciliacao?bank=${bank.id}&from=${d}&to=${d}`,'Movimento atualizado.'));});
  r.post('/conciliacao/movimentos/:id/excluir',async(req,res,ctx,q,p)=>{if(!C.requireAdmin(ctx,res))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,t=get('SELECT * FROM bank_transactions WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!t)return C.redirect(res,'/conciliacao');if(t.reconciled)return C.redirect(res,C.flashUrl(`/conciliacao?bank=${t.bank_account_id}`,'Movimento conciliado não pode ser excluído. Desvincule primeiro.','warn'));run('DELETE FROM bank_transactions WHERE id=:id AND organization_id=:o',{id:t.id,o});C.audit(ctx,req,'DELETE','bank_transactions',t.id,t,null);C.redirect(res,C.flashUrl(`/conciliacao?bank=${t.bank_account_id}`,'Movimento do extrato excluído.'));});

  r.get('/conciliacao/importar',async(req,res,ctx,q)=>{if(!C.requirePerm(ctx,res,'reconciliation','import'))return;const banks=bankOptions(ctx.user.organization_id);const f=`<div class="panel-body"><p>Suporta <b>OFX</b>, <b>XLSX</b> e <b>CSV</b>. CSV: <code>data;descricao;valor;documento</code>. Valor positivo = entrada; negativo = saída.</p></div><form method="post" enctype="multipart/form-data" action="/conciliacao/importar">${U.csrf(ctx)}${U.formGrid(U.select('bank_account_id','Conta bancária',q.bank||'',banks,{required:true})+`<label class="field"><span>Arquivo OFX, XLSX ou CSV <span class="field-help-icon" title="Importe o extrato da conta bancária selecionada. O arquivo deve representar movimentos do banco, não lançamentos do Financeiro.">?</span></span><input type="file" name="file" accept=".ofx,.xlsx,.csv" required></label>`,`<a class="btn" href="/conciliacao">Cancelar</a><button class="btn primary">Importar extrato</button>`)}</form>`;C.send(res,200,U.layout(ctx,'Importar extrato',U.panel('Importação bancária',f),'/conciliacao',{msg:q.msg,mt:q.mt}));});
  r.post('/conciliacao/importar',async(req,res,ctx)=>{if(!C.requirePerm(ctx,res,'reconciliation','import'))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,bank=get('SELECT * FROM bank_accounts WHERE id=:id AND organization_id=:o AND active=1',{id:b.bank_account_id,o});if(!bank||!b.file?.data)return C.redirect(res,C.flashUrl('/conciliacao/importar','Conta e arquivo são obrigatórios.','err'));const text=b.file.data.toString('utf8'),fn=String(b.file.filename||'').toLowerCase();let raw=fn.endsWith('.ofx')?C.parseOFX(text):fn.endsWith('.xlsx')?C.parseXLSX(b.file.data):C.parseCSV(text);let rows=fn.endsWith('.ofx')?raw:raw.map(x=>({tx_date:C.normDate(x.data||x.tx_date||x.date),description:x.descricao||x.description||x.memo||'Movimento',amount:C.num(x.valor||x.amount||'0'),document_number:x.documento||x.document_number||'',external_id:x.id||x.fitid||''}));const batch='BANK-'+Date.now();let count=0,dups=0;transaction(()=>{for(const x of rows){if(!x.tx_date||!Number.isFinite(Number(x.amount))||Math.abs(Number(x.amount))<0.005)continue;if(x.external_id&&get('SELECT id FROM bank_transactions WHERE organization_id=:o AND bank_account_id=:b AND external_id=:e',{o,b:bank.id,e:x.external_id})){dups++;continue;}if(!x.external_id&&get(`SELECT id FROM bank_transactions WHERE organization_id=:o AND bank_account_id=:b AND tx_date=:d AND ABS(amount-:a)<0.005 AND description=:desc AND imported=1`,{o,b:bank.id,d:x.tx_date,a:Number(x.amount),desc:x.description||'Movimento'})){dups++;continue;}run(`INSERT INTO bank_transactions(id,organization_id,bank_account_id,tx_date,description,amount,document_number,external_id,imported,import_batch,reconciled,movement_origin,created_by,created_at,updated_at) VALUES(:id,:o,:b,:d,:desc,:amt,:doc,:ext,1,:batch,0,'STATEMENT',:u,:t,:t)`,{id:id(),o,b:bank.id,d:x.tx_date,desc:x.description||'Movimento',amt:Number(x.amount),doc:x.document_number||'',ext:x.external_id||'',batch,u:ctx.user.id,t:now()});count++;}});C.audit(ctx,req,'IMPORT','bank_transactions',batch,null,{rows:count,duplicates:dups,bank:bank.name});C.redirect(res,C.flashUrl(`/conciliacao?bank=${bank.id}`,`${count} movimento(s) importado(s); ${dups} duplicado(s) ignorado(s).`));});

  r.get('/conciliacao/:id/vincular',async(req,res,ctx,q,p)=>{if(!C.requirePerm(ctx,res,'reconciliation','edit'))return;const o=ctx.user.organization_id,tx=get('SELECT * FROM bank_transactions WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!tx)return C.send(res,404,C.errorPage('Movimento não encontrado',''));if(tx.reconciled)return C.redirect(res,C.flashUrl(`/conciliacao?bank=${tx.bank_account_id}`,'Movimento já conciliado.','warn'));const type=Number(tx.amount)>=0?'RECEIVABLE':'PAYABLE',amt=Math.abs(Number(tx.amount));const pays=all(`SELECT p.*,fe.description,fe.document_number FROM financial_payments p JOIN financial_entries fe ON fe.id=p.financial_entry_id WHERE p.organization_id=:o AND p.bank_account_id=:b AND p.active=1 AND p.reconciled=0 AND fe.entry_type=:type ORDER BY ABS(julianday(p.movement_date)-julianday(:d)),p.movement_date DESC LIMIT 300`,{o,b:tx.bank_account_id,type,d:tx.tx_date});const payOpts=pays.map(x=>[x.id,`${U.dateBR(x.movement_date)} · ${x.description} · ${U.money(x.amount)}${Math.abs(Number(x.amount)-amt)<.005?' · VALOR EXATO':''}`]);const entries=all(`SELECT * FROM financial_entries WHERE organization_id=:o AND entry_type=:type AND status NOT IN ('PAID','CANCELLED') AND (amount-paid_amount)>0.005 ORDER BY ABS(julianday(due_date)-julianday(:d)),due_date DESC LIMIT 300`,{o,type,d:tx.tx_date});const entryOpts=entries.map(e=>[e.id,`${U.dateBR(e.due_date)} · ${e.description} · saldo ${U.money(e.amount-e.paid_amount)}`]);const f=`<div class="detail-grid"><div class="detail"><small>Data do extrato</small><b>${U.dateBR(tx.tx_date)}</b></div><div class="detail"><small>Descrição</small><b>${C.esc(tx.description)}</b></div><div class="detail"><small>Valor</small><b>${U.money(tx.amount)}</b></div></div><div class="alert ok"><b>Opção 1:</b> vincule a uma baixa já registrada no Financeiro. <b>Opção 2:</b> selecione um lançamento ainda em aberto; o sistema criará a baixa usando a data, banco e valor deste extrato.</div><form method="post" action="/conciliacao/${tx.id}/vincular">${U.csrf(ctx)}${U.formGrid(U.select('payment_id','Baixa financeira existente','',payOpts,{blankLabel:'Não usar baixa existente'})+U.select('entry_id','OU lançamento financeiro em aberto','',entryOpts,{blankLabel:'Não criar baixa a partir do extrato'}),`<a class="btn" href="/conciliacao?bank=${tx.bank_account_id}">Cancelar</a><button class="btn primary">Vincular e conciliar</button>`)}</form>`;C.send(res,200,U.layout(ctx,'Vincular extrato ao Financeiro',U.panel('Conciliação manual',f),'/conciliacao',{msg:q.msg,mt:q.mt}));});
  r.post('/conciliacao/:id/vincular',async(req,res,ctx,q,p)=>{if(!C.requirePerm(ctx,res,'reconciliation','edit'))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,tx=get('SELECT * FROM bank_transactions WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!tx||tx.reconciled)return C.redirect(res,C.flashUrl('/conciliacao','Movimento inválido ou já conciliado.','err'));const type=Number(tx.amount)>=0?'RECEIVABLE':'PAYABLE',amt=Math.abs(Number(tx.amount));let pay=null,e=null,created=false;if(b.payment_id){pay=get(`SELECT p.*,fe.entry_type FROM financial_payments p JOIN financial_entries fe ON fe.id=p.financial_entry_id WHERE p.id=:id AND p.organization_id=:o AND p.active=1 AND p.reconciled=0`,{id:b.payment_id,o});if(!pay||pay.bank_account_id!==tx.bank_account_id||pay.entry_type!==type)return C.redirect(res,C.flashUrl(`/conciliacao/${tx.id}/vincular`,'A baixa selecionada não corresponde ao banco/tipo do extrato.','err'));if(Math.abs(Number(pay.amount)-amt)>.005)return C.redirect(res,C.flashUrl(`/conciliacao/${tx.id}/vincular`,`O valor da baixa (${U.money(pay.amount)}) não é igual ao valor do extrato (${U.money(amt)}). Ajuste a baixa ou selecione um lançamento em aberto.`,'err'));e=get('SELECT * FROM financial_entries WHERE id=:id AND organization_id=:o',{id:pay.financial_entry_id,o});}else if(b.entry_id){e=get('SELECT * FROM financial_entries WHERE id=:id AND organization_id=:o AND entry_type=:type AND status NOT IN (\'PAID\',\'CANCELLED\')',{id:b.entry_id,o,type});if(!e)return C.redirect(res,C.flashUrl(`/conciliacao/${tx.id}/vincular`,'Lançamento inválido.','err'));const remaining=Number(e.amount)-Number(e.paid_amount);if(amt>remaining+.005)return C.redirect(res,C.flashUrl(`/conciliacao/${tx.id}/vincular`,`O extrato é maior que o saldo do lançamento (${U.money(remaining)}). Faça o ajuste antes de conciliar.`,'err'));pay={id:id(),financial_entry_id:e.id,amount:amt};created=true;}else return C.redirect(res,C.flashUrl(`/conciliacao/${tx.id}/vincular`,'Selecione uma baixa existente ou um lançamento em aberto.','err'));
    transaction(()=>{if(created){const t=now();run(`INSERT INTO financial_payments(id,organization_id,financial_entry_id,movement_date,amount,bank_account_id,payment_method,document_number,notes,active,reconciled,bank_transaction_id,source,created_by,created_at,updated_at) VALUES(:id,:o,:e,:d,:a,:b,'Extrato bancário',:doc,'Baixa criada a partir da conciliação do extrato.',1,1,:tx,'STATEMENT',:u,:t,:t)`,{id:pay.id,o,e:e.id,d:tx.tx_date,a:amt,b:tx.bank_account_id,doc:tx.document_number||'',tx:tx.id,u:ctx.user.id,t});recalcEntry(o,e.id);}else run('UPDATE financial_payments SET reconciled=1,bank_transaction_id=:tx,updated_at=:t WHERE id=:id AND organization_id=:o',{tx:tx.id,t:now(),id:pay.id,o});run('UPDATE bank_transactions SET reconciled=1,financial_entry_id=:e,financial_payment_id=:p,updated_at=:t WHERE id=:id AND organization_id=:o',{e:e.id,p:pay.id,t:now(),id:tx.id,o});});C.audit(ctx,req,'RECONCILE','bank_transactions',tx.id,tx,{financial_entry_id:e.id,financial_payment_id:pay.id,created_payment:created});C.redirect(res,C.flashUrl(`/conciliacao?bank=${tx.bank_account_id}&from=${tx.tx_date}&to=${tx.tx_date}`,'Movimento conciliado com o Financeiro.'));});

  r.post('/conciliacao/:id/desvincular',async(req,res,ctx,q,p)=>{if(!C.requireAdmin(ctx,res))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,tx=get('SELECT * FROM bank_transactions WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!tx)return C.redirect(res,'/conciliacao');transaction(()=>{if(tx.financial_payment_id)run('UPDATE financial_payments SET reconciled=0,bank_transaction_id=NULL,updated_at=:t WHERE id=:id AND organization_id=:o',{t:now(),id:tx.financial_payment_id,o});run('UPDATE bank_transactions SET reconciled=0,financial_entry_id=NULL,financial_payment_id=NULL,updated_at=:t WHERE id=:id AND organization_id=:o',{t:now(),id:tx.id,o});});C.audit(ctx,req,'UNRECONCILE','bank_transactions',tx.id,tx,{reconciled:0});C.redirect(res,C.flashUrl(`/conciliacao?bank=${tx.bank_account_id}`,'Vínculo removido. A baixa financeira foi preservada e voltou a ficar pendente de conciliação.'));});

  r.post('/conciliacao/auto',async(req,res,ctx)=>{if(!C.requirePerm(ctx,res,'reconciliation','approve'))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,bank=get('SELECT * FROM bank_accounts WHERE id=:id AND organization_id=:o',{id:b.bank_id,o});if(!bank)return C.redirect(res,'/conciliacao');const f=C.normDate(b.from)||'1900-01-01',to=C.normDate(b.to)||'2999-12-31',txs=all('SELECT * FROM bank_transactions WHERE organization_id=:o AND bank_account_id=:b AND reconciled=0 AND tx_date BETWEEN :f AND :t ORDER BY tx_date',{o,b:bank.id,f,t:to});let matched=0;transaction(()=>{for(const tx of txs){const type=Number(tx.amount)>=0?'RECEIVABLE':'PAYABLE',amt=Math.abs(Number(tx.amount));const cand=all(`SELECT p.*,fe.entry_type FROM financial_payments p JOIN financial_entries fe ON fe.id=p.financial_entry_id WHERE p.organization_id=:o AND p.bank_account_id=:b AND p.active=1 AND p.reconciled=0 AND fe.entry_type=:type AND ABS(p.amount-:amt)<0.005 AND ABS(julianday(p.movement_date)-julianday(:d))<=3 ORDER BY ABS(julianday(p.movement_date)-julianday(:d)) LIMIT 2`,{o,b:bank.id,type,amt,d:tx.tx_date});if(cand.length===1){const p=cand[0];run('UPDATE bank_transactions SET reconciled=1,financial_entry_id=:e,financial_payment_id=:p,updated_at=:t WHERE id=:id',{e:p.financial_entry_id,p:p.id,t:now(),id:tx.id});run('UPDATE financial_payments SET reconciled=1,bank_transaction_id=:tx,updated_at=:t WHERE id=:id',{tx:tx.id,t:now(),id:p.id});matched++;}}});C.audit(ctx,req,'AUTO_RECONCILE','bank_transactions',bank.id,null,{matched,from:f,to});C.redirect(res,C.flashUrl(`/conciliacao?bank=${bank.id}&from=${f}&to=${to}`,`${matched} movimento(s) conciliado(s) automaticamente com baixas financeiras de mesmo valor e data próxima.`));});
};
