'use strict';
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {run,get,all,id,now,transaction}=require('./db');
const C=require('./core');
const U=require('./ui');
const S=require('./schedule');

const ROOT=path.join(__dirname,'..');
const UPLOADS=path.join(ROOT,'uploads');
const DOC_TYPES=[['CONTRACT','Contrato'],['AMENDMENT','Aditivo'],['POLICY','Apólice'],['MINUTES','Ata'],['CCT','CCT / instrumento coletivo'],['PROPOSAL','Proposta / medição'],['OTHER','Outro documento']];
const ADJ_TYPES=[['RENEWAL','Renovação'],['REPACTUATION','Repactuação'],['REAJUSTMENT','Reajuste'],['AMENDMENT','Aditivo financeiro'],['OTHER','Outro']];

function nOr(v,fallback){return String(v??'').trim()===''?Number(fallback||0):C.num(v);}
function dateDiffInclusive(a,b){if(!a||!b||b<a)return 0;const d1=new Date(a+'T12:00:00Z'),d2=new Date(b+'T12:00:00Z');return Math.floor((d2-d1)/86400000)+1;}
function calcAdjustment(baseValue,newValue,effective,until){
  const base=Number(baseValue||0),nv=Number(newValue||0),diff=nv-base,pct=base?diff/base*100:0,days=dateDiffInclusive(effective,until),retro=days?diff/30*days:0;
  return{base,newValue:nv,diff,pct,days,retro,measurement:nv};
}
function fmtPct(v){return `${Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:4})}%`;}
function typeLabel(type,items){return items.find(x=>x[0]===type)?.[1]||type||'-';}
function safeFileName(name){return path.basename(String(name||'documento')).replace(/[\r\n\0]/g,'').slice(0,180);}
function uploadExt(name){const ext=path.extname(name).toLowerCase();return ['.pdf','.doc','.docx','.xls','.xlsx','.jpg','.jpeg','.png','.txt','.csv'].includes(ext)?ext:'';}
function contractDeadline(c){
  const s=C.statusContract(c.end_date,c.renewal_status,c.active),d=s.days;
  if(d===null||d===undefined)return{html:'<div class="alert warn"><b>Prazo contratual não calculado.</b> Confira a data final da vigência.</div>',text:'Sem prazo'};
  if(d<0)return{html:`<div class="alert danger"><b>CONTRATO VENCIDO HÁ ${Math.abs(d)} DIA(S).</b> Vigência encerrada em ${U.dateBR(c.end_date)}. Registre renovação, encerramento ou aguardando renovação.</div>`,text:`Vencido há ${Math.abs(d)} dia(s)`};
  if(d===0)return{html:`<div class="alert danger"><b>CONTRATO VENCE HOJE.</b> Data final: ${U.dateBR(c.end_date)}.</div>`,text:'Vence hoje'};
  if(d<=4)return{html:`<div class="alert danger"><b>ALERTA CRÍTICO: faltam ${d} dia(s).</b> O contrato vence em ${U.dateBR(c.end_date)}.</div>`,text:`${d} dia(s)`};
  if(d<=30)return{html:`<div class="alert warn"><b>ATENÇÃO: faltam ${d} dias para o vencimento.</b> Data final: ${U.dateBR(c.end_date)}.</div>`,text:`${d} dias`};
  if(d<=90)return{html:`<div class="alert warn"><b>Janela de renovação: faltam ${d} dias.</b> Vencimento em ${U.dateBR(c.end_date)}.</div>`,text:`${d} dias`};
  return{html:`<div class="alert ok"><b>Contrato vigente.</b> Faltam ${d} dias para ${U.dateBR(c.end_date)}.</div>`,text:`${d} dias`};
}
function recalcInventory(itemId,o){
  let stock=0;for(const m of all(`SELECT * FROM inventory_movements WHERE item_id=:id AND organization_id=:o ORDER BY CASE WHEN movement_type='ADJUSTMENT' AND reference='SALDO INICIAL' THEN 0 ELSE 1 END,occurred_at,created_at,id`,{id:itemId,o})){
    const q=Number(m.quantity||0);if(m.movement_type==='ADJUSTMENT')stock=q;else if(['IN','RETURN'].includes(m.movement_type))stock+=Math.abs(q);else if(m.movement_type==='OUT')stock-=Math.abs(q);
  }run('UPDATE inventory_items SET current_stock=:s,updated_at=:t WHERE id=:id AND organization_id=:o',{s:stock,t:now(),id:itemId,o});return stock;
}
function recalcUniform(uniformId,o){
  let stock=0;for(const m of all(`SELECT * FROM uniform_movements WHERE uniform_id=:id AND organization_id=:o ORDER BY CASE WHEN movement_type='ADJUSTMENT' AND reason='SALDO INICIAL' THEN 0 ELSE 1 END,movement_date,created_at,id`,{id:uniformId,o})){
    const q=Number(m.quantity||0);if(m.movement_type==='ADJUSTMENT')stock=q;else if(['PURCHASE','RETURN'].includes(m.movement_type))stock+=Math.abs(q);else if(['DELIVERY','LOSS','EXCHANGE'].includes(m.movement_type))stock-=Math.abs(q);
  }run('UPDATE uniform_catalog SET current_stock=:s,updated_at=:t WHERE id=:id AND organization_id=:o',{s:stock,t:now(),id:uniformId,o});return stock;
}
function recalcAsset(assetId,o){
  const maint=get("SELECT id FROM asset_maintenances WHERE asset_id=:id AND organization_id=:o AND status='OPEN' LIMIT 1",{id:assetId,o});
  const alloc=get('SELECT id FROM asset_allocations WHERE asset_id=:id AND organization_id=:o AND active=1 LIMIT 1',{id:assetId,o});
  run('UPDATE assets SET status=:s,updated_at=:t WHERE id=:id AND organization_id=:o',{s:maint?'MAINTENANCE':alloc?'ALLOCATED':'AVAILABLE',t:now(),id:assetId,o});
}
function optionsEmployees(o){return all('SELECT id,name,registration,status FROM employees WHERE organization_id=:o ORDER BY status=\'ACTIVE\' DESC,name',{o}).map(e=>[e.id,`${e.name}${e.registration?' · '+e.registration:''}${e.status!=='ACTIVE'?' · '+e.status:''}`]);}
function optionsContracts(o){return all(`SELECT co.id,COALESCE(NULLIF(cl.trade_name,''),cl.legal_name)||' · '||COALESCE(co.contract_number,'Contrato') name FROM contracts co JOIN clients cl ON cl.id=co.client_id WHERE co.organization_id=:o ORDER BY co.end_date DESC`,{o}).map(x=>[x.id,x.name]);}

module.exports=function(r){
  // ===== CONTRATOS: renovação v2.4 com memória de cálculo =====
  r.get('/contratos/:id/renovar',async(req,res,ctx,q,p)=>{
    if(!C.requirePerm(ctx,res,'clients','edit'))return;const o=ctx.user.organization_id;
    const c=get(`SELECT co.*,cl.legal_name,cl.trade_name FROM contracts co JOIN clients cl ON cl.id=co.client_id WHERE co.id=:id AND co.organization_id=:o`,{id:p.id,o});if(!c)return C.send(res,404,C.errorPage('Contrato não encontrado',''));
    const child=get('SELECT id,contract_number FROM contracts WHERE previous_contract_id=:id AND organization_id=:o ORDER BY version_number DESC LIMIT 1',{id:c.id,o});if(child)return C.redirect(res,C.flashUrl(`/contratos/${c.id}`,`Este contrato já foi renovado para ${child.contract_number||'uma nova versão'}.`,'warn'));
    const series=c.series_id||c.id,maxv=Number(get('SELECT COALESCE(MAX(version_number),1)v FROM contracts WHERE organization_id=:o AND series_id=:s',{o,s:series}).v||1),nextv=maxv+1;
    const start=S.addDays(c.end_date,1)||C.localDate(),duration=Math.max(0,S.daysDiff(c.start_date,c.end_date)),end=S.addDays(start,duration),retroUntil=S.addDays(start,-1)||c.end_date;
    const deadline=contractDeadline(c);
    const preview=`${deadline.html}<div class="grid">${U.card('Versão atual',`V${c.version_number||1}`)}${U.card('Contrato atual',C.esc(c.contract_number||'Sem número'))}${U.card('Vigência',`${U.dateBR(c.start_date)} → ${U.dateBR(c.end_date)}`)}${U.card('Valor atual',U.money(c.monthly_value))}</div><div class="alert warn"><b>A renovação cria uma nova versão.</b> O contrato anterior, seus postos, colaboradores, valores, documentos e histórico permanecem preservados.</div>`;
    const calc=`<div class="form-grid"><div class="detail"><small>Valor-base</small><b id="calcBase">${U.money(c.monthly_value)}</b></div><div class="detail"><small>Diferença mensal</small><b id="calcDiff">${U.money(0)}</b></div><div class="detail"><small>Percentual</small><b id="calcPct">0,00%</b></div><div class="detail"><small>Dias retroativos (pró-rata 30)</small><b id="calcDays">0</b></div><div class="detail"><small>Retroativo calculado</small><b id="calcRetro">${U.money(0)}</b></div><div class="detail"><small>Nova medição mensal</small><b id="calcMeasurement">${U.money(c.monthly_value)}</b></div></div>`;
    const fields=U.input('contract_number','Novo número do contrato',String(c.contract_number||'')?`${c.contract_number}-R${nextv}`:`VERSAO-${nextv}`,{required:true})+
      U.input('start_date','Nova vigência - início',start,{type:'date',required:true})+U.input('end_date','Nova vigência - fim',end,{type:'date',required:true})+
      U.input('monthly_value','Novo valor mensal',c.monthly_value,{type:'number',step:'0.01',min:0})+
      U.input('measurement_value_final','Valor da medição mensal (editável)',c.monthly_value,{type:'number',step:'0.01',min:0})+
      U.input('retroactive_amount_final','Valor retroativo a cobrar (editável)',0,{type:'number',step:'0.01'})+
      U.select('adjustment_type','Natureza do ajuste','RENEWAL',ADJ_TYPES,{blank:false})+
      U.input('cct_name','CCT / instrumento coletivo','')+U.input('cct_reference','Número / referência da CCT','')+
      U.input('cct_base_date','Data-base da CCT','',{type:'date'})+U.input('signed_date','Data de assinatura/aprovação do reajuste',C.localDate(),{type:'date'})+
      U.input('financial_effective_date','Efeito financeiro desde',c.last_reajust_date||c.end_date,{type:'date'})+U.input('retroactive_until_date','Calcular retroativo até',retroUntil,{type:'date'})+
      U.input('uniform_exchange_days','Prazo de troca de fardamento (dias)',c.uniform_exchange_days||180,{type:'number',min:1})+U.input('billing_day','Dia de faturamento',c.billing_day||'',{type:'number',min:1})+
      U.input('reajust_index','Índice / regra de reajuste',c.reajust_index||'')+U.input('manager_name','Gestor / responsável no cliente',c.manager_name||'')+
      U.input('manager_phone','Contato do gestor',c.manager_phone||'')+U.textarea('description','Escopo / descrição da nova versão',c.description||'',{rows:4})+
      U.textarea('renewal_note','Observação da renovação','Renovação contratual',{rows:3})+
      `<div class="field span2"><span>O que levar para a nova versão?</span>${U.check('copy_posts','Copiar postos e dimensionamento atuais',true)}${U.check('copy_allocations','Transferir alocações ativas para os postos copiados',true)}</div>`+
      U.textarea('calculation_notes','Memória / observação do cálculo','O retroativo automático usa a diferença mensal dividida por 30 e multiplicada pelos dias do período informado. O valor final é editável.',{rows:3})+U.textarea('notes','Observações do novo contrato',c.notes||'',{rows:3});
    const script=`<script>(function(){const q=n=>Number(String(n||'').replace(',','.'))||0,br=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),base=${Number(c.monthly_value||0)};function d(){const nv=q(document.querySelector('[name=monthly_value]').value),diff=nv-base,pct=base?diff/base*100:0,e=document.querySelector('[name=financial_effective_date]').value,u=document.querySelector('[name=retroactive_until_date]').value;let days=0;if(e&&u&&u>=e)days=Math.floor((new Date(u+'T12:00:00Z')-new Date(e+'T12:00:00Z'))/86400000)+1;const retro=diff/30*days;document.getElementById('calcDiff').textContent=br(diff);document.getElementById('calcPct').textContent=pct.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:4})+'%';document.getElementById('calcDays').textContent=days;document.getElementById('calcRetro').textContent=br(retro);document.getElementById('calcMeasurement').textContent=br(nv);const rf=document.querySelector('[name=retroactive_amount_final]'),mf=document.querySelector('[name=measurement_value_final]');if(!rf.dataset.touched)rf.value=retro.toFixed(2);if(!mf.dataset.touched)mf.value=nv.toFixed(2)}document.querySelectorAll('[name=monthly_value],[name=financial_effective_date],[name=retroactive_until_date]').forEach(x=>x.addEventListener('input',d));document.querySelectorAll('[name=retroactive_amount_final],[name=measurement_value_final]').forEach(x=>x.addEventListener('input',()=>x.dataset.touched='1'));d()})();</script>`;
    const form=`<form method="post" action="/contratos/${c.id}/renovar">${U.csrf(ctx)}${U.formGrid(fields,`<a class="btn" href="/contratos/${c.id}">Cancelar</a><button class="btn primary" data-confirm="Criar nova versão e preservar integralmente o contrato anterior?">Renovar e criar nova versão</button>`)}</form>${script}`;
    C.send(res,200,U.layout(ctx,'Renovar contrato',preview+U.panel('Memória de cálculo da repactuação',calc)+U.panel(`${c.trade_name||c.legal_name} · nova versão V${nextv}`,form),'/clientes',{msg:q.msg,mt:q.mt}));
  });

  r.post('/contratos/:id/renovar',async(req,res,ctx,q,p)=>{
    if(!C.requirePerm(ctx,res,'clients','edit'))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));
    const o=ctx.user.organization_id,c=get('SELECT * FROM contracts WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!c)return C.send(res,404,C.errorPage('Contrato não encontrado',''));
    const child=get('SELECT id,contract_number FROM contracts WHERE previous_contract_id=:id AND organization_id=:o LIMIT 1',{id:c.id,o});if(child)return C.redirect(res,C.flashUrl(`/contratos/${c.id}`,`Este contrato já possui uma renovação: ${child.contract_number||child.id}.`,'warn'));
    if(!b.start_date||!b.end_date||b.end_date<b.start_date)return C.redirect(res,C.flashUrl(`/contratos/${c.id}/renovar`,'Informe uma nova vigência válida.','err'));
    const series=c.series_id||c.id,nextv=Number(get('SELECT COALESCE(MAX(version_number),1)+1 v FROM contracts WHERE organization_id=:o AND series_id=:s',{o,s:series}).v||2);
    const newId=id(),eventId=id(),adjId=id(),t=now(),copyAlloc=C.bool(b.copy_allocations),copyPosts=C.bool(b.copy_posts)||copyAlloc,postMap=new Map(),allocationMap=new Map();
    const nv=C.num(b.monthly_value),eff=b.financial_effective_date||b.start_date,until=b.retroactive_until_date||S.addDays(b.start_date,-1),calc=calcAdjustment(c.monthly_value,nv,eff,until),retroFinal=nOr(b.retroactive_amount_final,calc.retro),measurementFinal=nOr(b.measurement_value_final,nv);
    transaction(()=>{
      run(`INSERT INTO contracts(id,organization_id,client_id,contract_number,description,start_date,end_date,renewal_status,monthly_value,uniform_exchange_days,manager_name,manager_phone,billing_day,reajust_index,last_reajust_date,notes,active,series_id,version_number,previous_contract_id,created_at,updated_at) VALUES(:id,:o,:cl,:num,:desc,:start,:end,'ACTIVE',:value,:days,:mn,:mp,:bd,:ri,:lr,:notes,1,:series,:v,:prev,:t,:t)`,{id:newId,o,cl:c.client_id,num:String(b.contract_number||'').trim(),desc:b.description||'',start:b.start_date,end:b.end_date,value:nv,days:Number(b.uniform_exchange_days||180),mn:b.manager_name||'',mp:b.manager_phone||'',bd:b.billing_day?Number(b.billing_day):null,ri:b.reajust_index||'',lr:b.signed_date||b.financial_effective_date||null,notes:b.notes||'',series,v:nextv,prev:c.id,t});
      const oldPosts=all('SELECT * FROM contract_posts WHERE contract_id=:id AND organization_id=:o',{id:c.id,o});if(copyPosts)for(const x of oldPosts.filter(x=>Number(x.active))){const np=id();postMap.set(x.id,np);run(`INSERT INTO contract_posts(id,organization_id,contract_id,post_name,post_type,headcount,shift_regime,schedule_details,armed,weapon_type,weapon_quantity,started_at,ended_at,active,notes,created_at,updated_at) VALUES(:id,:o,:c,:n,:type,:hc,:sr,:sd,:a,:wt,:wq,:s,NULL,1,:notes,:t,:t)`,{id:np,o,c:newId,n:x.post_name,type:x.post_type||'',hc:Number(x.headcount||1),sr:x.shift_regime||'',sd:x.schedule_details||'',a:Number(x.armed||0),wt:x.weapon_type||'',wq:Number(x.weapon_quantity||0),s:b.start_date,notes:x.notes||'',t});}
      const oldAllocs=all(`SELECT * FROM employee_allocations WHERE contract_id=:id AND organization_id=:o AND active=1 AND (end_date IS NULL OR end_date='' OR end_date>=:start)`,{id:c.id,o,start:b.start_date});if(copyAlloc)for(const a of oldAllocs){const na=id();allocationMap.set(a.id,na);const carriedEnd=a.end_date&&a.end_date>=b.start_date?(a.end_date>b.end_date?b.end_date:a.end_date):null;run(`INSERT INTO employee_allocations(id,organization_id,employee_id,contract_id,post_id,start_date,end_date,shift_regime,active,work_pattern,day_parity,cycle_anchor_date,shift_start,shift_end,allocation_role,relief_employee_id,covers_employee_id,notes,created_at,updated_at) VALUES(:id,:o,:e,:c,:p,:start,:end,:shift,1,:wp,:par,:anchor,:ss,:se,:role,:relief,:covers,:notes,:t,:t)`,{id:na,o,e:a.employee_id,c:newId,p:a.post_id?(postMap.get(a.post_id)||null):null,start:b.start_date,end:carriedEnd,shift:a.shift_regime||'',wp:a.work_pattern||'CUSTOM',par:a.day_parity||'',anchor:a.cycle_anchor_date||b.start_date,ss:a.shift_start||'',se:a.shift_end||'',role:a.allocation_role||'TITULAR',relief:a.relief_employee_id||null,covers:a.covers_employee_id||null,notes:a.notes||'',t});}
      if(copyAlloc){const oldReps=all(`SELECT * FROM schedule_replacements WHERE contract_id=:c AND organization_id=:o AND end_date>=:start`,{c:c.id,o,start:b.start_date});for(const x of oldReps){const mapped=allocationMap.get(x.original_allocation_id);if(!mapped)continue;const nr=id(),ns=x.start_date>b.start_date?x.start_date:b.start_date;if(x.end_date<ns)continue;run(`INSERT INTO schedule_replacements(id,organization_id,contract_id,post_id,original_allocation_id,absent_employee_id,substitute_employee_id,absence_id,start_date,end_date,replacement_type,shift_start,shift_end,reason,notes,active,created_by,created_at,updated_at) VALUES(:id,:o,:c,:p,:a,:absent,:sub,:absence,:s,:e,:type,:ss,:se,:r,:notes,1,:by,:t,:t)`,{id:nr,o,c:newId,p:x.post_id?(postMap.get(x.post_id)||null):null,a:mapped,absent:x.absent_employee_id,sub:x.substitute_employee_id,absence:x.absence_id||null,s:ns,e:x.end_date,type:x.replacement_type||'COVERAGE',ss:x.shift_start||'',se:x.shift_end||'',r:x.reason||'',notes:x.notes||'',by:ctx.user.id,t});}}
      run(`UPDATE schedule_replacements SET active=0,end_date=CASE WHEN end_date>:d THEN :d ELSE end_date END,updated_at=:t WHERE contract_id=:id AND organization_id=:o`,{d:c.end_date,t,id:c.id,o});
      run(`UPDATE employee_allocations SET active=0,end_date=CASE WHEN end_date IS NULL OR end_date>:d THEN :d ELSE end_date END,updated_at=:t WHERE contract_id=:id AND organization_id=:o AND active=1`,{d:c.end_date,t,id:c.id,o});
      run(`UPDATE contract_posts SET active=0,ended_at=CASE WHEN ended_at IS NULL OR ended_at>:d THEN :d ELSE ended_at END,updated_at=:t WHERE contract_id=:id AND organization_id=:o AND active=1`,{d:c.end_date,t,id:c.id,o});
      run(`UPDATE contracts SET active=0,renewal_status='RENEWED',renewed_at=:t,renewal_note=:note,closed_at=:d,closure_reason='Renovado para nova versão',updated_at=:t WHERE id=:id AND organization_id=:o`,{t,note:b.renewal_note||'',d:c.end_date,id:c.id,o});
      run(`INSERT INTO contract_renewals(id,organization_id,client_id,series_id,previous_contract_id,new_contract_id,renewal_number,renewed_at,effective_from,previous_number,new_number,previous_start_date,previous_end_date,new_start_date,new_end_date,previous_monthly_value,new_monthly_value,note,copied_posts,copied_allocations,created_by,created_at) VALUES(:id,:o,:cl,:series,:prev,:new,:n,:at,:eff,:pn,:nn,:ps,:pe,:ns,:ne,:pv,:nv,:note,:cp,:ca,:by,:t)`,{id:eventId,o,cl:c.client_id,series,prev:c.id,new:newId,n:nextv-1,at:t,eff:b.start_date,pn:c.contract_number||'',nn:String(b.contract_number||''),ps:c.start_date,pe:c.end_date,ns:b.start_date,ne:b.end_date,pv:Number(c.monthly_value||0),nv,note:b.renewal_note||'',cp:copyPosts,ca:copyAlloc,by:ctx.user.id,t});
      run(`INSERT INTO contract_adjustments(id,organization_id,series_id,contract_id,previous_contract_id,adjustment_type,title,base_monthly_value,new_monthly_value,monthly_difference,percentage,cct_name,cct_reference,cct_base_date,signed_date,financial_effective_date,retroactive_until_date,retroactive_days,retroactive_amount_calculated,retroactive_amount_final,measurement_value_calculated,measurement_value_final,calculation_method,notes,created_by,created_at,updated_at) VALUES(:id,:o,:series,:c,:prev,:type,:title,:base,:nv,:diff,:pct,:cct,:ref,:baseDate,:signed,:eff,:until,:days,:retro,:retroFinal,:measurement,:measurementFinal,'PRO_RATA_30',:notes,:by,:t,:t)`,{id:adjId,o,series,c:newId,prev:c.id,type:b.adjustment_type||'RENEWAL',title:`${typeLabel(b.adjustment_type||'RENEWAL',ADJ_TYPES)} ${c.contract_number||''} → ${b.contract_number||''}`.trim(),base:Number(c.monthly_value||0),nv,diff:calc.diff,pct:calc.pct,cct:b.cct_name||'',ref:b.cct_reference||'',baseDate:b.cct_base_date||null,signed:b.signed_date||null,eff:eff||null,until:until||null,days:calc.days,retro:calc.retro,retroFinal,measurement:nv,measurementFinal,notes:b.calculation_notes||'',by:ctx.user.id,t});
    });
    C.audit(ctx,req,'RENEW','contracts',c.id,{contract_number:c.contract_number,monthly_value:c.monthly_value},{new_contract_id:newId,new_contract_number:b.contract_number,monthly_value:nv,difference:calc.diff,retroactive_amount:retroFinal,measurement_value:measurementFinal,cct:b.cct_name||''});
    C.redirect(res,C.flashUrl(`/contratos/${newId}/repactuacoes`,`Contrato renovado para V${nextv}. Memória de reajuste/repactuação registrada.`));
  });

  // ===== DOCUMENTAÇÃO CONTRATUAL =====
  r.get('/contratos/:id/documentos',async(req,res,ctx,q,p)=>{
    if(!C.requirePerm(ctx,res,'clients'))return;const o=ctx.user.organization_id,c=get(`SELECT co.*,cl.legal_name,cl.trade_name FROM contracts co JOIN clients cl ON cl.id=co.client_id WHERE co.id=:id AND co.organization_id=:o`,{id:p.id,o});if(!c)return C.send(res,404,C.errorPage('Contrato não encontrado',''));
    const docs=all(`SELECT d.*,u.name uploaded_name FROM contract_documents d LEFT JOIN users u ON u.id=d.uploaded_by WHERE d.contract_id=:c AND d.organization_id=:o ORDER BY d.created_at DESC`,{c:c.id,o});
    const today=C.localDate(),rows=docs.map(d=>{let exp='-';if(d.expiration_date){const days=S.daysDiff(today,d.expiration_date);exp=days<0?U.badge(`Vencido há ${Math.abs(days)} dia(s)`,'danger'):days<=30?U.badge(`Vence em ${days} dia(s)`,'warn'):U.badge(U.dateBR(d.expiration_date),'ok')}return `<tr><td>${U.badge(typeLabel(d.document_type,DOC_TYPES),'info')}</td><td><b>${C.esc(d.title)}</b><br><small>${C.esc(d.original_name)}</small></td><td>${U.dateBR(d.reference_date)}</td><td>${exp}</td><td>${C.esc(d.uploaded_name||'-')}<br><small>${U.dateTimeBR(d.created_at)}</small></td><td><div class="row-actions"><a class="btn sm" href="/documentos-contrato/${d.id}/baixar">Baixar</a>${C.isAdmin(ctx)?`<form method="post" action="/documentos-contrato/${d.id}/excluir">${U.csrf(ctx)}<button class="btn sm danger" data-confirm="Excluir definitivamente este arquivo do contrato?">Excluir</button></form>`:''}</div></td></tr>`});
    const form=C.can(ctx,'clients','edit')?`<form method="post" action="/contratos/${c.id}/documentos" enctype="multipart/form-data">${U.csrf(ctx)}${U.formGrid(U.select('document_type','Tipo','CONTRACT',DOC_TYPES,{blank:false})+U.input('title','Título / identificação','',{required:true})+U.input('reference_date','Data de referência','',{type:'date'})+U.input('expiration_date','Vencimento do documento','',{type:'date'})+`<label class="field span2"><span>Arquivo * (PDF, Word, Excel, JPG ou PNG; até 15 MB) <span class="field-help-icon" title="Anexe o documento que comprova ou complementa este contrato. Use o tipo e o vencimento para facilitar alertas futuros.">?</span></span><input type="file" name="file" required accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png,.txt,.csv"><small class="field-help"><span class="help-dot">i</span>Anexe o documento correspondente a este contrato. Para apólices e documentos com validade, informe também o vencimento para receber alertas.</small></label>`+U.textarea('notes','Observações','',{rows:3}),`<button class="btn primary">Anexar documentação</button>`)}</form>`:'';
    const deadline=contractDeadline(c);C.send(res,200,U.layout(ctx,'Documentos do contrato',deadline.html+U.panel(`${c.contract_number||'Contrato'} · ${c.trade_name||c.legal_name}`,form||'<div class="panel-body muted">Seu usuário possui somente leitura.</div>')+U.panel('Documentos anexados',U.table(['Tipo','Documento','Referência','Vencimento','Enviado por','Ações'],rows)),'/clientes',{msg:q.msg,mt:q.mt,actions:`<a class="btn" href="/contratos/${c.id}">← Contrato</a><a class="btn" href="/contratos/${c.id}/repactuacoes">Repactuações</a>`}));
  });
  r.post('/contratos/:id/documentos',async(req,res,ctx,q,p)=>{
    if(!C.requirePerm(ctx,res,'clients','edit'))return;let b;try{b=await C.parseBody(req)}catch(e){return C.send(res,413,C.errorPage('Arquivo muito grande',e.message))}if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));
    const o=ctx.user.organization_id,c=get('SELECT * FROM contracts WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!c)return C.send(res,404,C.errorPage('Contrato não encontrado',''));const f=b.file;if(!f||!Buffer.isBuffer(f.data)||!f.filename)return C.redirect(res,C.flashUrl(`/contratos/${c.id}/documentos`,'Selecione um arquivo.','err'));
    if(f.data.length>15*1024*1024)return C.redirect(res,C.flashUrl(`/contratos/${c.id}/documentos`,'Arquivo acima de 15 MB.','err'));const ext=uploadExt(f.filename);if(!ext)return C.redirect(res,C.flashUrl(`/contratos/${c.id}/documentos`,'Tipo de arquivo não permitido.','err'));
    const did=id(),dir=path.join(UPLOADS,'contracts',o,c.id);fs.mkdirSync(dir,{recursive:true});const stored=did+ext,file=path.join(dir,stored);fs.writeFileSync(file,f.data,{flag:'wx'});const rel=path.relative(UPLOADS,file).replace(/\\/g,'/'),hash=crypto.createHash('sha256').update(f.data).digest('hex');
    try{run(`INSERT INTO contract_documents(id,organization_id,contract_id,document_type,title,reference_date,expiration_date,notes,original_name,stored_name,mime_type,size_bytes,sha256,uploaded_by,created_at) VALUES(:id,:o,:c,:type,:title,:ref,:exp,:notes,:original,:stored,:mime,:size,:hash,:by,:t)`,{id:did,o,c:c.id,type:DOC_TYPES.some(x=>x[0]===b.document_type)?b.document_type:'OTHER',title:String(b.title||safeFileName(f.filename)).trim(),ref:b.reference_date||null,exp:b.expiration_date||null,notes:b.notes||'',original:safeFileName(f.filename),stored:rel,mime:String(f.mime||'application/octet-stream').slice(0,120),size:f.data.length,hash,by:ctx.user.id,t:now()});}catch(e){try{fs.unlinkSync(file)}catch{}throw e}
    C.audit(ctx,req,'DOCUMENT_UPLOAD','contract_documents',did,null,{contract_id:c.id,title:b.title,file:safeFileName(f.filename),bytes:f.data.length,sha256:hash});C.redirect(res,C.flashUrl(`/contratos/${c.id}/documentos`,'Documento anexado e registrado no histórico.'));
  });
  r.get('/documentos-contrato/:id/baixar',async(req,res,ctx,q,p)=>{
    if(!C.requirePerm(ctx,res,'clients'))return;const o=ctx.user.organization_id,d=get('SELECT * FROM contract_documents WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!d)return C.send(res,404,C.errorPage('Documento não encontrado',''));const file=path.resolve(UPLOADS,d.stored_name);if(!file.startsWith(path.resolve(UPLOADS)+path.sep)||!fs.existsSync(file))return C.send(res,404,C.errorPage('Arquivo físico não encontrado','O registro existe, mas o arquivo não está na pasta uploads. Restaure um backup completo.'));const buf=fs.readFileSync(file);res.statusCode=200;res.setHeader('Content-Type','application/octet-stream');res.setHeader('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(d.original_name)}`);res.setHeader('Content-Length',buf.length);res.setHeader('X-Content-Type-Options','nosniff');res.end(buf);
  });
  r.post('/documentos-contrato/:id/excluir',async(req,res,ctx,q,p)=>{
    if(!C.requireAdmin(ctx,res))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,d=get('SELECT * FROM contract_documents WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!d)return C.redirect(res,'/clientes');run('DELETE FROM contract_documents WHERE id=:id AND organization_id=:o',{id:d.id,o});try{fs.unlinkSync(path.resolve(UPLOADS,d.stored_name))}catch{}C.audit(ctx,req,'DELETE','contract_documents',d.id,d,null);C.redirect(res,C.flashUrl(`/contratos/${d.contract_id}/documentos`,'Documento excluído pelo administrador.'));
  });

  // ===== REPACTUAÇÕES / REAJUSTES independentes =====
  r.get('/contratos/:id/repactuacoes',async(req,res,ctx,q,p)=>{
    if(!C.requirePerm(ctx,res,'clients'))return;const o=ctx.user.organization_id,c=get(`SELECT co.*,cl.legal_name,cl.trade_name FROM contracts co JOIN clients cl ON cl.id=co.client_id WHERE co.id=:id AND co.organization_id=:o`,{id:p.id,o});if(!c)return C.send(res,404,C.errorPage('Contrato não encontrado',''));const series=c.series_id||c.id,adj=all(`SELECT a.*,co.contract_number FROM contract_adjustments a JOIN contracts co ON co.id=a.contract_id WHERE a.organization_id=:o AND a.series_id=:s ORDER BY COALESCE(a.financial_effective_date,a.created_at) DESC,a.created_at DESC`,{o,s:series});
    const rows=adj.map(a=>`<tr><td>${U.dateBR(a.financial_effective_date)}<br><small>registrado ${U.dateTimeBR(a.created_at)}</small></td><td>${U.badge(typeLabel(a.adjustment_type,ADJ_TYPES),'info')}<br><small>${C.esc(a.contract_number||'')}</small></td><td>${U.money(a.base_monthly_value)} → <b>${U.money(a.new_monthly_value)}</b><br><small>${fmtPct(a.percentage)}</small></td><td><b>${U.money(a.monthly_difference)}</b></td><td>${C.esc(a.cct_name||'-')}<br><small>${C.esc(a.cct_reference||'')} ${a.cct_base_date?'· base '+U.dateBR(a.cct_base_date):''}</small></td><td>${a.retroactive_days} dia(s)<br><b>${U.money(a.retroactive_amount_final)}</b><br><small>auto: ${U.money(a.retroactive_amount_calculated)}</small></td><td><b>${U.money(a.measurement_value_final)}</b><br><small>auto: ${U.money(a.measurement_value_calculated)}</small></td><td>${C.can(ctx,'clients','edit')?`<a class="btn sm" href="/repactuacoes/${a.id}/editar">Editar</a>`:''}${C.isAdmin(ctx)?`<form method="post" action="/repactuacoes/${a.id}/excluir" style="display:inline">${U.csrf(ctx)}<button class="btn sm danger" data-confirm="Excluir este registro financeiro de repactuação?">Excluir</button></form>`:''}</td></tr>`);
    const last=adj[0];const cards=`<div class="grid">${U.card('Valor atual',U.money(c.monthly_value))}${U.card('Última diferença',last?U.money(last.monthly_difference):'-')}${U.card('Retroativo registrado',last?U.money(last.retroactive_amount_final):'-')}${U.card('Medição atual',last?U.money(last.measurement_value_final):U.money(c.monthly_value))}</div>`;
    C.send(res,200,U.layout(ctx,'Repactuações e medições',contractDeadline(c).html+cards+U.panel('Memória financeira da série contratual',U.table(['Efeito','Tipo','Valor mensal','Diferença','CCT / data-base','Retroativo','Medição','Ações'],rows)),'/clientes',{msg:q.msg,mt:q.mt,actions:`<a class="btn" href="/contratos/${c.id}">← Contrato</a><a class="btn" href="/contratos/${c.id}/documentos">Documentos</a>${C.can(ctx,'clients','edit')?`<a class="btn primary" href="/contratos/${c.id}/repactuacao/nova">Nova repactuação / reajuste</a>`:''}`}));
  });
  function adjustmentForm(ctx,c,a={},action){const base=a.base_monthly_value??c.monthly_value,nv=a.new_monthly_value??c.monthly_value,eff=a.financial_effective_date||C.localDate(),until=a.retroactive_until_date||C.localDate();return `<form method="post" action="${action}">${U.csrf(ctx)}${U.formGrid(U.select('adjustment_type','Tipo',a.adjustment_type||'REPACTUATION',ADJ_TYPES,{blank:false})+U.input('title','Título / referência',a.title||'')+U.input('base_monthly_value','Valor-base mensal',base,{type:'number',step:'0.01'})+U.input('new_monthly_value','Novo valor mensal',nv,{type:'number',step:'0.01'})+U.input('measurement_value_final','Valor da medição (editável)',a.measurement_value_final??nv,{type:'number',step:'0.01'})+U.input('retroactive_amount_final','Retroativo final (editável)',a.retroactive_amount_final??0,{type:'number',step:'0.01'})+U.input('cct_name','CCT / instrumento coletivo',a.cct_name||'')+U.input('cct_reference','Referência / número da CCT',a.cct_reference||'')+U.input('cct_base_date','Data-base',a.cct_base_date||'',{type:'date'})+U.input('signed_date','Data do reajuste / assinatura',a.signed_date||C.localDate(),{type:'date'})+U.input('financial_effective_date','Efeito financeiro desde',eff,{type:'date'})+U.input('retroactive_until_date','Retroativo até',until,{type:'date'})+U.check('apply_value_to_contract','Atualizar o valor mensal deste contrato com o novo valor',false)+U.textarea('notes','Memória / observações',a.notes||'Cálculo automático: diferença mensal ÷ 30 × dias retroativos. O valor final permanece editável.',{rows:4}),`<a class="btn" href="/contratos/${c.id}/repactuacoes">Cancelar</a><button class="btn primary">Salvar memória de cálculo</button>`)}</form>`;}
  r.get('/contratos/:id/repactuacao/nova',async(req,res,ctx,q,p)=>{if(!C.requirePerm(ctx,res,'clients','edit'))return;const c=get('SELECT * FROM contracts WHERE id=:id AND organization_id=:o',{id:p.id,o:ctx.user.organization_id});if(!c)return C.send(res,404,C.errorPage('Contrato não encontrado',''));C.send(res,200,U.layout(ctx,'Nova repactuação / reajuste',contractDeadline(c).html+U.panel(c.contract_number||'Contrato',adjustmentForm(ctx,c,{},`/contratos/${c.id}/repactuacoes`)),'/clientes',{msg:q.msg,mt:q.mt}));});
  r.post('/contratos/:id/repactuacoes',async(req,res,ctx,q,p)=>{if(!C.requirePerm(ctx,res,'clients','edit'))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,c=get('SELECT * FROM contracts WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!c)return C.send(res,404,C.errorPage('Contrato não encontrado',''));const base=C.num(b.base_monthly_value),nv=C.num(b.new_monthly_value),calc=calcAdjustment(base,nv,b.financial_effective_date,b.retroactive_until_date),retro=nOr(b.retroactive_amount_final,calc.retro),measure=nOr(b.measurement_value_final,nv),aid=id(),t=now();transaction(()=>{run(`INSERT INTO contract_adjustments(id,organization_id,series_id,contract_id,previous_contract_id,adjustment_type,title,base_monthly_value,new_monthly_value,monthly_difference,percentage,cct_name,cct_reference,cct_base_date,signed_date,financial_effective_date,retroactive_until_date,retroactive_days,retroactive_amount_calculated,retroactive_amount_final,measurement_value_calculated,measurement_value_final,calculation_method,notes,created_by,created_at,updated_at) VALUES(:id,:o,:s,:c,:prev,:type,:title,:base,:nv,:diff,:pct,:cct,:ref,:bd,:signed,:eff,:until,:days,:auto,:final,:mAuto,:mFinal,'PRO_RATA_30',:notes,:by,:t,:t)`,{id:aid,o,s:c.series_id||c.id,c:c.id,prev:c.previous_contract_id||null,type:b.adjustment_type||'REPACTUATION',title:b.title||'',base,nv,diff:calc.diff,pct:calc.pct,cct:b.cct_name||'',ref:b.cct_reference||'',bd:b.cct_base_date||null,signed:b.signed_date||null,eff:b.financial_effective_date||null,until:b.retroactive_until_date||null,days:calc.days,auto:calc.retro,final:retro,mAuto:nv,mFinal:measure,notes:b.notes||'',by:ctx.user.id,t});if(C.bool(b.apply_value_to_contract))run('UPDATE contracts SET monthly_value=:v,last_reajust_date=:d,updated_at=:t WHERE id=:id AND organization_id=:o',{v:nv,d:b.signed_date||b.financial_effective_date||null,t,id:c.id,o});});C.audit(ctx,req,'ADJUSTMENT_CREATE','contract_adjustments',aid,null,{contract_id:c.id,base,new_value:nv,difference:calc.diff,retroactive:retro,measurement:measure,cct:b.cct_name});C.redirect(res,C.flashUrl(`/contratos/${c.id}/repactuacoes`,'Repactuação/reajuste registrado com memória de cálculo.'));});
  r.get('/repactuacoes/:id/editar',async(req,res,ctx,q,p)=>{if(!C.requirePerm(ctx,res,'clients','edit'))return;const o=ctx.user.organization_id,a=get('SELECT * FROM contract_adjustments WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!a)return C.send(res,404,C.errorPage('Registro não encontrado',''));const c=get('SELECT * FROM contracts WHERE id=:id AND organization_id=:o',{id:a.contract_id,o});C.send(res,200,U.layout(ctx,'Editar repactuação / reajuste',U.panel(a.title||c.contract_number||'Memória financeira',adjustmentForm(ctx,c,a,`/repactuacoes/${a.id}`)),'/clientes',{msg:q.msg,mt:q.mt}));});
  r.post('/repactuacoes/:id',async(req,res,ctx,q,p)=>{if(!C.requirePerm(ctx,res,'clients','edit'))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,a=get('SELECT * FROM contract_adjustments WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!a)return C.send(res,404,C.errorPage('Registro não encontrado',''));const base=C.num(b.base_monthly_value),nv=C.num(b.new_monthly_value),calc=calcAdjustment(base,nv,b.financial_effective_date,b.retroactive_until_date),retro=nOr(b.retroactive_amount_final,calc.retro),measure=nOr(b.measurement_value_final,nv),before={...a};transaction(()=>{run(`UPDATE contract_adjustments SET adjustment_type=:type,title=:title,base_monthly_value=:base,new_monthly_value=:nv,monthly_difference=:diff,percentage=:pct,cct_name=:cct,cct_reference=:ref,cct_base_date=:bd,signed_date=:signed,financial_effective_date=:eff,retroactive_until_date=:until,retroactive_days=:days,retroactive_amount_calculated=:auto,retroactive_amount_final=:final,measurement_value_calculated=:ma,measurement_value_final=:mf,notes=:notes,updated_at=:t WHERE id=:id AND organization_id=:o`,{type:b.adjustment_type||'REPACTUATION',title:b.title||'',base,nv,diff:calc.diff,pct:calc.pct,cct:b.cct_name||'',ref:b.cct_reference||'',bd:b.cct_base_date||null,signed:b.signed_date||null,eff:b.financial_effective_date||null,until:b.retroactive_until_date||null,days:calc.days,auto:calc.retro,final:retro,ma:nv,mf:measure,notes:b.notes||'',t:now(),id:a.id,o});if(C.bool(b.apply_value_to_contract))run('UPDATE contracts SET monthly_value=:v,last_reajust_date=:d,updated_at=:t WHERE id=:id AND organization_id=:o',{v:nv,d:b.signed_date||b.financial_effective_date||null,t:now(),id:a.contract_id,o});});C.audit(ctx,req,'ADJUSTMENT_UPDATE','contract_adjustments',a.id,before,{new_value:nv,difference:calc.diff,retroactive:retro,measurement:measure});C.redirect(res,C.flashUrl(`/contratos/${a.contract_id}/repactuacoes`,'Memória financeira atualizada.'));});
  r.post('/repactuacoes/:id/excluir',async(req,res,ctx,q,p)=>{if(!C.requireAdmin(ctx,res))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,a=get('SELECT * FROM contract_adjustments WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!a)return C.redirect(res,'/clientes');run('DELETE FROM contract_adjustments WHERE id=:id AND organization_id=:o',{id:a.id,o});C.audit(ctx,req,'DELETE','contract_adjustments',a.id,a,null);C.redirect(res,C.flashUrl(`/contratos/${a.contract_id}/repactuacoes`,'Registro de repactuação excluído pelo administrador.'));});

  // ===== LOG OPERACIONAL DO COLABORADOR =====
  r.get('/colaboradores/:id/log',async(req,res,ctx,q,p)=>{
    if(!C.requirePerm(ctx,res,'employees'))return;const o=ctx.user.organization_id,e=get('SELECT * FROM employees WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!e)return C.send(res,404,C.errorPage('Colaborador não encontrado',''));
    const uniforms=all(`SELECT uc.id uniform_id,uc.name,uc.size,SUM(CASE um.movement_type WHEN 'DELIVERY' THEN um.quantity WHEN 'RETURN' THEN -um.quantity WHEN 'LOSS' THEN -um.quantity ELSE 0 END) held FROM uniform_movements um JOIN uniform_catalog uc ON uc.id=um.uniform_id WHERE um.organization_id=:o AND um.employee_id=:e GROUP BY uc.id,uc.name,uc.size HAVING ABS(held)>0.0001 ORDER BY uc.name,uc.size`,{o,e:e.id});
    const inventory=all(`SELECT ii.id item_id,ii.name,ii.unit,SUM(CASE im.movement_type WHEN 'OUT' THEN im.quantity WHEN 'RETURN' THEN -im.quantity ELSE 0 END) held FROM inventory_movements im JOIN inventory_items ii ON ii.id=im.item_id WHERE im.organization_id=:o AND im.employee_id=:e GROUP BY ii.id,ii.name,ii.unit HAVING ABS(held)>0.0001 ORDER BY ii.name`,{o,e:e.id});
    const assets=all(`SELECT a.id,a.name,a.patrimony_code,a.asset_type,aa.id allocation_id,aa.allocated_at,co.contract_number FROM asset_allocations aa JOIN assets a ON a.id=aa.asset_id LEFT JOIN contracts co ON co.id=aa.contract_id WHERE aa.organization_id=:o AND aa.employee_id=:e AND aa.active=1 ORDER BY aa.allocated_at DESC`,{o,e:e.id});
    const urows=uniforms.map(x=>`<tr><td><a href="/uniformes/${x.uniform_id}/movimentar"><b>${C.esc(x.name)}</b></a></td><td>${C.esc(x.size||'-')}</td><td class="right"><b>${Number(x.held).toLocaleString('pt-BR')}</b></td></tr>`),irows=inventory.map(x=>`<tr><td><a href="/estoque/${x.item_id}/movimentar"><b>${C.esc(x.name)}</b></a></td><td>${C.esc(x.unit||'UN')}</td><td class="right"><b>${Number(x.held).toLocaleString('pt-BR')}</b></td></tr>`),arows=assets.map(x=>`<tr><td><a href="/patrimonio/${x.id}"><b>${C.esc(x.name)}</b></a><br><small>${C.esc(x.patrimony_code||'')}</small></td><td>${C.esc(x.asset_type)}</td><td>${U.dateBR(x.allocated_at)}</td><td>${C.esc(x.contract_number||'-')}</td></tr>`);
    const events=[];for(const x of all(`SELECT um.*,uc.name item,uc.size,co.contract_number FROM uniform_movements um JOIN uniform_catalog uc ON uc.id=um.uniform_id LEFT JOIN contracts co ON co.id=um.contract_id WHERE um.organization_id=:o AND um.employee_id=:e`,{o,e:e.id}))events.push({date:x.movement_date,kind:'Uniforme',desc:`${x.movement_type}: ${x.item} ${x.size||''}`,qty:x.quantity,ref:x.contract_number||x.reason||''});for(const x of all(`SELECT im.*,ii.name item FROM inventory_movements im JOIN inventory_items ii ON ii.id=im.item_id WHERE im.organization_id=:o AND im.employee_id=:e`,{o,e:e.id}))events.push({date:String(x.occurred_at).slice(0,10),kind:'Estoque',desc:`${x.movement_type}: ${x.item}`,qty:x.quantity,ref:x.reference||''});for(const x of all(`SELECT aa.*,a.name item FROM asset_allocations aa JOIN assets a ON a.id=aa.asset_id WHERE aa.organization_id=:o AND aa.employee_id=:e`,{o,e:e.id})){events.push({date:aaDate(x,'allocated_at'),kind:'Patrimônio',desc:`Alocação: ${x.item}`,qty:'1',ref:x.condition_out||''});if(x.returned_at)events.push({date:aaDate(x,'returned_at'),kind:'Patrimônio',desc:`Devolução: ${x.item}`,qty:'1',ref:x.condition_return||''});}events.sort((a,b)=>String(b.date).localeCompare(String(a.date)));function aaDate(x,k){return String(x[k]||'').slice(0,10)}
    const erows=events.slice(0,500).map(x=>`<tr><td>${U.dateBR(x.date)}</td><td>${U.badge(x.kind,x.kind==='Uniforme'?'info':x.kind==='Patrimônio'?'warn':'muted')}</td><td>${C.esc(x.desc)}</td><td class="right">${C.esc(x.qty)}</td><td>${C.esc(x.ref||'-')}</td></tr>`);
    const cards=`<div class="grid">${U.card('Uniformes em posse',uniforms.reduce((s,x)=>s+Number(x.held||0),0).toLocaleString('pt-BR'))}${U.card('Materiais em posse',inventory.reduce((s,x)=>s+Number(x.held||0),0).toLocaleString('pt-BR'))}${U.card('Patrimônios alocados',assets.length)}${U.card('Eventos rastreados',events.length)}</div>`;
    C.send(res,200,U.layout(ctx,'Log do colaborador',cards+U.panel('Uniformes atualmente com o colaborador',U.table(['Item','Tamanho','Quantidade em posse'],urows))+U.panel('Materiais de estoque atualmente com o colaborador',U.table(['Item','Unidade','Quantidade em posse'],irows))+U.panel('Patrimônios atualmente alocados',U.table(['Bem','Tipo','Desde','Contrato'],arows))+U.panel('Linha do tempo operacional',U.table(['Data','Módulo','Movimento','Quantidade','Referência'],erows)),'/colaboradores',{msg:q.msg,mt:q.mt,actions:`<a class="btn" href="/colaboradores/${e.id}/editar">← Cadastro</a>`}));
  });


  r.post('/alocacoes/:id/excluir',async(req,res,ctx,q,p)=>{if(!C.requireAdmin(ctx,res))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,a=get('SELECT * FROM employee_allocations WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!a)return C.redirect(res,'/colaboradores');const reps=all('SELECT * FROM schedule_replacements WHERE original_allocation_id=:id AND organization_id=:o',{id:a.id,o});run('DELETE FROM employee_allocations WHERE id=:id AND organization_id=:o',{id:a.id,o});C.audit(ctx,req,'DELETE','employee_allocations',a.id,{...a,replacements_linked:reps},null);C.redirect(res,C.flashUrl(`/contratos/${a.contract_id}`,`Alocação excluída pelo administrador. ${reps.length} substituição(ões) histórica(s) permaneceram no banco sem o vínculo direto da alocação.`,'warn'));});

  // ===== CRUD ADMINISTRATIVO E EDIÇÃO DE MOVIMENTOS =====
  r.post('/estoque/:id/excluir',async(req,res,ctx,q,p)=>{if(!C.requireAdmin(ctx,res))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,i=get('SELECT * FROM inventory_items WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!i)return C.redirect(res,'/estoque');const moves=all('SELECT * FROM inventory_movements WHERE item_id=:id AND organization_id=:o ORDER BY occurred_at',{id:i.id,o});const operational=moves.filter(m=>!(m.movement_type==='ADJUSTMENT'&&m.reference==='SALDO INICIAL'&&!m.employee_id&&!m.client_id&&!m.contract_id));if(operational.length)return C.redirect(res,C.flashUrl('/estoque',`Não é possível excluir ${i.name}: existem ${operational.length} movimentação(ões) operacionais. Isso preserva o log dos colaboradores. Se algum movimento foi lançado por engano, abra o item e exclua/corrija o movimento específico; se o item não será mais usado, desmarque “Item ativo”.`,'warn'));transaction(()=>run('DELETE FROM inventory_items WHERE id=:id AND organization_id=:o',{id:i.id,o}));C.audit(ctx,req,'DELETE','inventory_items',i.id,{...i,movements:moves},null);C.redirect(res,C.flashUrl('/estoque','Item sem histórico operacional excluído pelo administrador.'));});
  r.get('/estoque/movimentos/:id/editar',async(req,res,ctx,q,p)=>{if(!C.requirePerm(ctx,res,'inventory','edit'))return;const o=ctx.user.organization_id,m=get(`SELECT m.*,i.name item_name FROM inventory_movements m JOIN inventory_items i ON i.id=m.item_id WHERE m.id=:id AND m.organization_id=:o`,{id:p.id,o});if(!m)return C.send(res,404,C.errorPage('Movimento não encontrado',''));const f=`<form method="post" action="/estoque/movimentos/${m.id}">${U.csrf(ctx)}${U.formGrid(U.select('movement_type','Tipo',m.movement_type,[['IN','Entrada'],['OUT','Saída'],['RETURN','Devolução'],['ADJUSTMENT','Ajuste de saldo']],{blank:false})+U.input('quantity',m.movement_type==='ADJUSTMENT'?'Saldo resultante':'Quantidade',m.quantity,{type:'number',step:'0.001',required:true})+U.input('unit_cost','Custo unitário',m.unit_cost||0,{type:'number',step:'0.01'})+U.select('employee_id','Colaborador',m.employee_id||'',optionsEmployees(o),{blankLabel:'Nenhum'})+U.input('reference','Referência',m.reference||'')+U.input('occurred_at','Data',String(m.occurred_at).slice(0,10),{type:'date',required:true})+U.textarea('notes','Observações',m.notes||''),`<a class="btn" href="/estoque/${m.item_id}/movimentar">Cancelar</a><button class="btn primary">Salvar e recalcular estoque</button>`)}</form>`;C.send(res,200,U.layout(ctx,'Editar movimento de estoque',U.panel(m.item_name,f),'/estoque',{msg:q.msg,mt:q.mt}));});
  r.post('/estoque/movimentos/:id',async(req,res,ctx,q,p)=>{if(!C.requirePerm(ctx,res,'inventory','edit'))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,m=get('SELECT * FROM inventory_movements WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!m)return C.send(res,404,C.errorPage('Movimento não encontrado',''));const before={...m},type=['IN','OUT','RETURN','ADJUSTMENT'].includes(b.movement_type)?b.movement_type:m.movement_type,qv=C.num(b.quantity);transaction(()=>{run(`UPDATE inventory_movements SET movement_type=:type,quantity=:q,unit_cost=:cost,employee_id=:e,reference=:ref,notes=:notes,occurred_at=:d WHERE id=:id AND organization_id=:o`,{type,q:qv,cost:C.num(b.unit_cost)||null,e:b.employee_id||null,ref:b.reference||'',notes:b.notes||'',d:(b.occurred_at||C.localDate())+'T12:00:00.000Z',id:m.id,o});recalcInventory(m.item_id,o);});C.audit(ctx,req,'MOVEMENT_UPDATE','inventory_movements',m.id,before,{type,quantity:qv});C.redirect(res,C.flashUrl(`/estoque/${m.item_id}/movimentar`,'Movimento alterado e saldo recalculado.'));});
  r.post('/estoque/movimentos/:id/excluir',async(req,res,ctx,q,p)=>{if(!C.requireAdmin(ctx,res))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,m=get('SELECT * FROM inventory_movements WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!m)return C.redirect(res,'/estoque');transaction(()=>{run('DELETE FROM inventory_movements WHERE id=:id AND organization_id=:o',{id:m.id,o});recalcInventory(m.item_id,o);});C.audit(ctx,req,'DELETE','inventory_movements',m.id,m,null);C.redirect(res,C.flashUrl(`/estoque/${m.item_id}/movimentar`,'Movimento excluído e saldo recalculado automaticamente.'));});

  r.post('/uniformes/:id/excluir',async(req,res,ctx,q,p)=>{if(!C.requireAdmin(ctx,res))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,i=get('SELECT * FROM uniform_catalog WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!i)return C.redirect(res,'/uniformes');const moves=all('SELECT * FROM uniform_movements WHERE uniform_id=:id AND organization_id=:o',{id:i.id,o});const operational=moves.filter(m=>!(m.movement_type==='ADJUSTMENT'&&m.reason==='SALDO INICIAL'&&!m.employee_id&&!m.contract_id));if(operational.length)return C.redirect(res,C.flashUrl('/uniformes',`Não é possível excluir ${i.name}: existem ${operational.length} movimentação(ões) operacionais. Isso preserva o histórico de entrega do colaborador. Corrija/exclua o movimento específico se ele foi lançado por engano ou desative o item se não será mais utilizado.`,'warn'));run('DELETE FROM uniform_catalog WHERE id=:id AND organization_id=:o',{id:i.id,o});C.audit(ctx,req,'DELETE','uniform_catalog',i.id,{...i,movements:moves},null);C.redirect(res,C.flashUrl('/uniformes','Uniforme sem histórico operacional excluído pelo administrador.'));});
  r.get('/uniformes/movimentos/:id/editar',async(req,res,ctx,q,p)=>{if(!C.requirePerm(ctx,res,'uniforms','edit'))return;const o=ctx.user.organization_id,m=get(`SELECT m.*,u.name item_name,u.size FROM uniform_movements m JOIN uniform_catalog u ON u.id=m.uniform_id WHERE m.id=:id AND m.organization_id=:o`,{id:p.id,o});if(!m)return C.send(res,404,C.errorPage('Movimento não encontrado',''));const f=`<form method="post" action="/uniformes/movimentos/${m.id}">${U.csrf(ctx)}${U.formGrid(U.select('movement_type','Tipo',m.movement_type,[['PURCHASE','Compra / entrada'],['DELIVERY','Entrega'],['RETURN','Devolução'],['EXCHANGE','Troca'],['LOSS','Perda / baixa'],['ADJUSTMENT','Ajuste de saldo']],{blank:false})+U.input('quantity',m.movement_type==='ADJUSTMENT'?'Saldo resultante':'Quantidade',m.quantity,{type:'number',step:'0.001',required:true})+U.select('employee_id','Colaborador',m.employee_id||'',optionsEmployees(o),{blankLabel:'Nenhum'})+U.select('contract_id','Contrato',m.contract_id||'',optionsContracts(o),{blankLabel:'Nenhum'})+U.input('movement_date','Data',m.movement_date,{type:'date',required:true})+U.input('next_exchange_date','Próxima troca',m.next_exchange_date||'',{type:'date'})+U.input('reason','Motivo / referência',m.reason||'')+U.textarea('condition_note','Condição / observações',m.condition_note||''),`<a class="btn" href="/uniformes/${m.uniform_id}/movimentar">Cancelar</a><button class="btn primary">Salvar e recalcular</button>`)}</form>`;C.send(res,200,U.layout(ctx,'Editar movimento de uniforme',U.panel(`${m.item_name} ${m.size||''}`,f),'/uniformes',{msg:q.msg,mt:q.mt}));});
  r.post('/uniformes/movimentos/:id',async(req,res,ctx,q,p)=>{if(!C.requirePerm(ctx,res,'uniforms','edit'))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,m=get('SELECT * FROM uniform_movements WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!m)return C.send(res,404,C.errorPage('Movimento não encontrado',''));const type=['PURCHASE','DELIVERY','RETURN','EXCHANGE','LOSS','ADJUSTMENT'].includes(b.movement_type)?b.movement_type:m.movement_type,qv=C.num(b.quantity),before={...m};transaction(()=>{run(`UPDATE uniform_movements SET movement_type=:type,quantity=:q,employee_id=:e,contract_id=:c,movement_date=:d,next_exchange_date=:next,reason=:r,condition_note=:n WHERE id=:id AND organization_id=:o`,{type,q:qv,e:b.employee_id||null,c:b.contract_id||null,d:b.movement_date||m.movement_date,next:b.next_exchange_date||null,r:b.reason||'',n:b.condition_note||'',id:m.id,o});recalcUniform(m.uniform_id,o);});C.audit(ctx,req,'MOVEMENT_UPDATE','uniform_movements',m.id,before,{type,quantity:qv,employee_id:b.employee_id});C.redirect(res,C.flashUrl(`/uniformes/${m.uniform_id}/movimentar`,'Movimento de uniforme alterado; estoque e log do colaborador foram recalculados.'));});
  r.post('/uniformes/movimentos/:id/excluir',async(req,res,ctx,q,p)=>{if(!C.requireAdmin(ctx,res))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,m=get('SELECT * FROM uniform_movements WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!m)return C.redirect(res,'/uniformes');transaction(()=>{run('DELETE FROM uniform_movements WHERE id=:id AND organization_id=:o',{id:m.id,o});recalcUniform(m.uniform_id,o);});C.audit(ctx,req,'DELETE','uniform_movements',m.id,m,null);C.redirect(res,C.flashUrl(`/uniformes/${m.uniform_id}/movimentar`,'Movimento excluído e saldo do uniforme recalculado automaticamente.'));});

  r.post('/patrimonio/:id/excluir',async(req,res,ctx,q,p)=>{if(!C.requireAdmin(ctx,res))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,a=get('SELECT * FROM assets WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!a)return C.redirect(res,'/patrimonio');const allocations=all('SELECT * FROM asset_allocations WHERE asset_id=:id AND organization_id=:o',{id:a.id,o}),maint=all('SELECT * FROM asset_maintenances WHERE asset_id=:id AND organization_id=:o',{id:a.id,o});if(allocations.length||maint.length)return C.redirect(res,C.flashUrl(`/patrimonio/${a.id}`,`Não é possível excluir definitivamente este patrimônio porque há ${allocations.length} alocação(ões) e ${maint.length} manutenção(ões) no histórico. O bloqueio preserva o log dos colaboradores. Você pode editar os dados e as alocações; se uma alocação estiver errada, exclua a alocação específica.`,'warn'));run('DELETE FROM assets WHERE id=:id AND organization_id=:o',{id:a.id,o});C.audit(ctx,req,'DELETE','assets',a.id,a,null);C.redirect(res,C.flashUrl('/patrimonio','Patrimônio sem histórico operacional excluído pelo administrador.'));});
  r.get('/patrimonio/alocacoes/:id/editar',async(req,res,ctx,q,p)=>{if(!C.requirePerm(ctx,res,'assets','edit'))return;const o=ctx.user.organization_id,a=get(`SELECT aa.*,x.name asset_name FROM asset_allocations aa JOIN assets x ON x.id=aa.asset_id WHERE aa.id=:id AND aa.organization_id=:o`,{id:p.id,o});if(!a)return C.send(res,404,C.errorPage('Alocação não encontrada',''));const clients=all('SELECT id,COALESCE(NULLIF(trade_name,\'\'),legal_name)name FROM clients WHERE organization_id=:o ORDER BY name',{o}).map(x=>[x.id,x.name]);const f=`<form method="post" action="/patrimonio/alocacoes/${a.id}">${U.csrf(ctx)}${U.formGrid(U.select('client_id','Cliente',a.client_id||'',clients,{blankLabel:'Base / sem cliente'})+U.select('contract_id','Contrato',a.contract_id||'',optionsContracts(o),{blankLabel:'Sem contrato'})+U.select('employee_id','Colaborador responsável',a.employee_id||'',optionsEmployees(o),{blankLabel:'Nenhum'})+U.input('allocated_at','Data de saída',a.allocated_at,{type:'date',required:true})+U.input('returned_at','Data de retorno',a.returned_at||'',{type:'date'})+U.input('condition_out','Condição na saída',a.condition_out||'')+U.input('condition_return','Condição na devolução',a.condition_return||''),`<a class="btn" href="/patrimonio/${a.asset_id}">Cancelar</a><button class="btn primary">Salvar alocação</button>`)}</form>`;C.send(res,200,U.layout(ctx,'Editar alocação patrimonial',U.panel(a.asset_name,f),'/patrimonio',{msg:q.msg,mt:q.mt}));});
  r.post('/patrimonio/alocacoes/:id',async(req,res,ctx,q,p)=>{if(!C.requirePerm(ctx,res,'assets','edit'))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,a=get('SELECT * FROM asset_allocations WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!a)return C.send(res,404,C.errorPage('Alocação não encontrada',''));const before={...a},active=b.returned_at?0:1;transaction(()=>{run(`UPDATE asset_allocations SET client_id=:cl,contract_id=:c,employee_id=:e,allocated_at=:d,returned_at=:r,condition_out=:co,condition_return=:cr,active=:a,updated_at=:t WHERE id=:id AND organization_id=:o`,{cl:b.client_id||null,c:b.contract_id||null,e:b.employee_id||null,d:b.allocated_at||a.allocated_at,r:b.returned_at||null,co:b.condition_out||'',cr:b.condition_return||'',a:active,t:now(),id:a.id,o});recalcAsset(a.asset_id,o);});C.audit(ctx,req,'ALLOCATION_UPDATE','asset_allocations',a.id,before,{employee_id:b.employee_id,contract_id:b.contract_id,returned_at:b.returned_at||null});C.redirect(res,C.flashUrl(`/patrimonio/${a.asset_id}`,'Alocação patrimonial atualizada e refletida no log do colaborador.'));});
  r.post('/patrimonio/alocacoes/:id/excluir',async(req,res,ctx,q,p)=>{if(!C.requireAdmin(ctx,res))return;const b=await C.parseBody(req);if(!C.csrfOk(ctx,b))return C.send(res,403,C.errorPage('Sessão inválida',''));const o=ctx.user.organization_id,a=get('SELECT * FROM asset_allocations WHERE id=:id AND organization_id=:o',{id:p.id,o});if(!a)return C.redirect(res,'/patrimonio');transaction(()=>{run('DELETE FROM asset_allocations WHERE id=:id AND organization_id=:o',{id:a.id,o});recalcAsset(a.asset_id,o);});C.audit(ctx,req,'DELETE','asset_allocations',a.id,a,null);C.redirect(res,C.flashUrl(`/patrimonio/${a.asset_id}`,'Alocação excluída e status patrimonial recalculado.'));});
};
